/*
 * @Author: MoCheng
 */
const data = [
  [{
    "pinyin": "akesushi",
    "real": "阿克苏市",
    "city_id": "652901"
  }, {
    "pinyin": "alukeerqinqi",
    "real": "阿鲁科尔沁旗",
    "city_id": "150421"
  }, {
    "pinyin": "anda",
    "real": "安达",
    "city_id": "231281"
  }, {
    "pinyin": "anfu",
    "real": "安福",
    "city_id": "360829"
  }, {
    "pinyin": "anhuaxian",
    "real": "安化县",
    "city_id": "430923"
  }, {
    "pinyin": "anjixian",
    "real": "安吉县",
    "city_id": "330523"
  }, {
    "pinyin": "ankang",
    "real": "安康",
    "city_id": "610900"
  }, {
    "pinyin": "anlushi",
    "real": "安陆市",
    "city_id": "420982"
  }, {
    "pinyin": "anning",
    "real": "安宁",
    "city_id": "530181"
  }, {
    "pinyin": "anping",
    "real": "安平",
    "city_id": "131125"
  }, {
    "pinyin": "anqing",
    "real": "安庆",
    "city_id": "340800"
  }, {
    "pinyin": "anqiushi",
    "real": "安丘市",
    "city_id": "370784"
  }, {
    "pinyin": "anrenxian",
    "real": "安仁县",
    "city_id": "431028"
  }, {
    "pinyin": "anshan",
    "real": "鞍山",
    "city_id": "210300"
  }, {
    "pinyin": "anshun",
    "real": "安顺",
    "city_id": "520400"
  }, {
    "pinyin": "anxiangxian",
    "real": "安乡县",
    "city_id": "430721"
  }, {
    "pinyin": "anxinxian",
    "real": "安新县",
    "city_id": "130632"
  }, {
    "pinyin": "anxixian",
    "real": "安溪县",
    "city_id": "350524"
  }, {
    "pinyin": "anyang",
    "real": "安阳",
    "city_id": "410500"
  }, {
    "pinyin": "anyi",
    "real": "安义",
    "city_id": "360123"
  }, {
    "pinyin": "anyuan",
    "real": "安远",
    "city_id": "360726"
  }, {
    "pinyin": "anyuexian",
    "real": "安岳县",
    "city_id": "512021"
  }, {
    "pinyin": "aohanqi",
    "real": "敖汉旗",
    "city_id": "150430"
  }],
  [{
    "pinyin": "beijing",
    "real": "北京",
    "city_id": "110100"
  }, {
    "pinyin": "badong",
    "real": "巴东",
    "city_id": "422823"
  }, {
    "pinyin": "baicheng",
    "real": "白城",
    "city_id": "220800"
  }, {
    "pinyin": "baiquan",
    "real": "拜泉",
    "city_id": "230231"
  }, {
    "pinyin": "baise",
    "real": "百色",
    "city_id": "451000"
  }, {
    "pinyin": "baishan",
    "real": "白山",
    "city_id": "220600"
  }, {
    "pinyin": "balinzuoqi",
    "real": "巴林左旗",
    "city_id": "150422"
  }, {
    "pinyin": "baodi",
    "real": "宝坻",
    "city_id": "120115"
  }, {
    "pinyin": "baoding",
    "real": "保定",
    "city_id": "130600"
  }, {
    "pinyin": "baofengxian",
    "real": "宝丰县",
    "city_id": "410421"
  }, {
    "pinyin": "baoji",
    "real": "宝鸡",
    "city_id": "610300"
  }, {
    "pinyin": "baoshan",
    "real": "保山",
    "city_id": "530500"
  }, {
    "pinyin": "baotou",
    "real": "包头",
    "city_id": "150200"
  }, {
    "pinyin": "baoyingxian",
    "real": "宝应县",
    "city_id": "321023"
  }, {
    "pinyin": "bayannaoer",
    "real": "巴彦淖尔",
    "city_id": "150800"
  }, {
    "pinyin": "bazhong",
    "real": "巴中",
    "city_id": "511900"
  }, {
    "pinyin": "bazhoushi",
    "real": "霸州市",
    "city_id": "131081"
  }, {
    "pinyin": "beihai",
    "real": "北海",
    "city_id": "450500"
  }, {
    "pinyin": "beizhen",
    "real": "北镇",
    "city_id": "210782"
  }, {
    "pinyin": "bengbu",
    "real": "蚌埠",
    "city_id": "340300"
  }, {
    "pinyin": "benxi",
    "real": "本溪",
    "city_id": "210500"
  }, {
    "pinyin": "benximanzuzizhixian",
    "real": "本溪满族自治县",
    "city_id": "210521"
  }, {
    "pinyin": "bijie",
    "real": "毕节",
    "city_id": "520500"
  }, {
    "pinyin": "binhaixian",
    "real": "滨海县",
    "city_id": "320922"
  }, {
    "pinyin": "binxian",
    "real": "彬县",
    "city_id": "610427"
  }, {
    "pinyin": "binxian",
    "real": "宾县",
    "city_id": "230125"
  }, {
    "pinyin": "binyang",
    "real": "宾阳",
    "city_id": "450126"
  }, {
    "pinyin": "binzhou",
    "real": "滨州",
    "city_id": "371600"
  }, {
    "pinyin": "bishan",
    "real": "璧山",
    "city_id": "500227"
  }, {
    "pinyin": "boaixian",
    "real": "博爱县",
    "city_id": "410822"
  }, {
    "pinyin": "boluoxian",
    "real": "博罗县",
    "city_id": "441322"
  }, {
    "pinyin": "botoushi",
    "real": "泊头市",
    "city_id": "130981"
  }, {
    "pinyin": "boxingxian",
    "real": "博兴县",
    "city_id": "371625"
  }, {
    "pinyin": "bozhou",
    "real": "亳州",
    "city_id": "341600"
  }],
  [{
    "pinyin": "cangnanxian",
    "real": "苍南县",
    "city_id": "330327"
  }, {
    "pinyin": "cangxi",
    "real": "苍溪",
    "city_id": "510824"
  }, {
    "pinyin": "cangzhou",
    "real": "沧州",
    "city_id": "130900"
  }, {
    "pinyin": "caofeidian",
    "real": "曹妃甸",
    "city_id": "130209"
  }, {
    "pinyin": "caoxian",
    "real": "曹县",
    "city_id": "371721"
  }, {
    "pinyin": "cenxi",
    "real": "岑溪",
    "city_id": "450481"
  }, {
    "pinyin": "chalingxian",
    "real": "茶陵县",
    "city_id": "430224"
  }, {
    "pinyin": "changchun",
    "real": "长春",
    "city_id": "220100"
  }, {
    "pinyin": "changde",
    "real": "常德",
    "city_id": "430700"
  }, {
    "pinyin": "changdu",
    "real": "昌都",
    "city_id": "542100"
  }, {
    "pinyin": "changfengxian",
    "real": "长丰县",
    "city_id": "340121"
  }, {
    "pinyin": "changgeshi",
    "real": "长葛市",
    "city_id": "411082"
  }, {
    "pinyin": "changji",
    "real": "昌吉",
    "city_id": "652301"
  }, {
    "pinyin": "changlexian",
    "real": "昌乐县",
    "city_id": "370725"
  }, {
    "pinyin": "changlingxian",
    "real": "长岭县",
    "city_id": "220722"
  }, {
    "pinyin": "changlixian",
    "real": "昌黎县",
    "city_id": "130322"
  }, {
    "pinyin": "changningshi",
    "real": "常宁市",
    "city_id": "430482"
  }, {
    "pinyin": "changsha",
    "real": "长沙",
    "city_id": "430100"
  }, {
    "pinyin": "changtingxian",
    "real": "长汀县",
    "city_id": "350821"
  }, {
    "pinyin": "changtuxian",
    "real": "昌图县",
    "city_id": "211224"
  }, {
    "pinyin": "changxingxian",
    "real": "长兴县",
    "city_id": "330522"
  }, {
    "pinyin": "changyangtujiazuzizhixian",
    "real": "长阳土家族自治县",
    "city_id": "420528"
  }, {
    "pinyin": "changyishi",
    "real": "昌邑市",
    "city_id": "370786"
  }, {
    "pinyin": "changyuanxian",
    "real": "长垣县",
    "city_id": "410728"
  }, {
    "pinyin": "changzhi",
    "real": "长治",
    "city_id": "140400"
  }, {
    "pinyin": "changzhou",
    "real": "常州",
    "city_id": "320400"
  }, {
    "pinyin": "chaohu",
    "real": "巢湖",
    "city_id": "340181"
  }, {
    "pinyin": "chaoyang",
    "real": "朝阳",
    "city_id": "211300"
  }, {
    "pinyin": "chaozhou",
    "real": "潮州",
    "city_id": "445100"
  }, {
    "pinyin": "chengde",
    "real": "承德",
    "city_id": "130800"
  }, {
    "pinyin": "chengdexian",
    "real": "承德县",
    "city_id": "130821"
  }, {
    "pinyin": "chengdu",
    "real": "成都",
    "city_id": "510100"
  }, {
    "pinyin": "chenggu",
    "real": "城固",
    "city_id": "610722"
  }, {
    "pinyin": "chengkou",
    "real": "城口",
    "city_id": "500229"
  }, {
    "pinyin": "chengwuxian",
    "real": "成武县",
    "city_id": "371723"
  }, {
    "pinyin": "chenzhou",
    "real": "郴州",
    "city_id": "431000"
  }, {
    "pinyin": "chibishi",
    "real": "赤壁市",
    "city_id": "421281"
  }, {
    "pinyin": "chifeng",
    "real": "赤峰",
    "city_id": "150400"
  }, {
    "pinyin": "chipingxian",
    "real": "茌平县",
    "city_id": "371523"
  }, {
    "pinyin": "chishui",
    "real": "赤水",
    "city_id": "520381"
  }, {
    "pinyin": "chizhou",
    "real": "池州",
    "city_id": "341700"
  }, {
    "pinyin": "chongqing",
    "real": "重庆",
    "city_id": "500100"
  }, {
    "pinyin": "chongyangxian",
    "real": "崇阳县",
    "city_id": "421223"
  }, {
    "pinyin": "chongzuo",
    "real": "崇左",
    "city_id": "451400"
  }, {
    "pinyin": "chunanxian",
    "real": "淳安县",
    "city_id": "330127"
  }, {
    "pinyin": "chuxiong",
    "real": "楚雄",
    "city_id": "532301"
  }, {
    "pinyin": "chuzhou",
    "real": "滁州",
    "city_id": "341100"
  }, {
    "pinyin": "cilixian",
    "real": "慈利县",
    "city_id": "430821"
  }, {
    "pinyin": "conghuashi",
    "real": "从化市",
    "city_id": "440184"
  }],
  [{
    "pinyin": "daanshi",
    "real": "大安市",
    "city_id": "220882"
  }, {
    "pinyin": "dachanghuizuzizhixian",
    "real": "大厂回族自治县",
    "city_id": "131028"
  }, {
    "pinyin": "dafengshi",
    "real": "大丰市",
    "city_id": "320982"
  }, {
    "pinyin": "dali",
    "real": "大理",
    "city_id": "532901"
  }, {
    "pinyin": "dali",
    "real": "大荔",
    "city_id": "610523"
  }, {
    "pinyin": "dalian",
    "real": "大连",
    "city_id": "210200"
  }, {
    "pinyin": "danchengxian",
    "real": "郸城县",
    "city_id": "411625"
  }, {
    "pinyin": "dandong",
    "real": "丹东",
    "city_id": "210600"
  }, {
    "pinyin": "dangshanxian",
    "real": "砀山县",
    "city_id": "341321"
  }, {
    "pinyin": "dangtuxian",
    "real": "当涂县",
    "city_id": "340521"
  }, {
    "pinyin": "dangyangshi",
    "real": "当阳市",
    "city_id": "420582"
  }, {
    "pinyin": "danjiangkoushi",
    "real": "丹江口市",
    "city_id": "420381"
  }, {
    "pinyin": "danyangshi",
    "real": "丹阳市",
    "city_id": "321181"
  }, {
    "pinyin": "danzhou",
    "real": "儋州",
    "city_id": "469003"
  }, {
    "pinyin": "daojiao",
    "real": "道滘",
    "city_id": "4419024"
  }, {
    "pinyin": "daoxian",
    "real": "道县",
    "city_id": "431124"
  }, {
    "pinyin": "daqing",
    "real": "大庆",
    "city_id": "230600"
  }, {
    "pinyin": "dashiqiaoshi",
    "real": "大石桥市",
    "city_id": "210882"
  }, {
    "pinyin": "datianxian",
    "real": "大田县",
    "city_id": "350425"
  }, {
    "pinyin": "datong",
    "real": "大同",
    "city_id": "140200"
  }, {
    "pinyin": "dawuxian",
    "real": "大悟县",
    "city_id": "420922"
  }, {
    "pinyin": "dayeshi",
    "real": "大冶市",
    "city_id": "420281"
  }, {
    "pinyin": "daying",
    "real": "大英",
    "city_id": "510923"
  }, {
    "pinyin": "dayixian",
    "real": "大邑县",
    "city_id": "510129"
  }, {
    "pinyin": "dazhou",
    "real": "达州",
    "city_id": "511700"
  }, {
    "pinyin": "dazhuxian",
    "real": "大竹县",
    "city_id": "511724"
  }, {
    "pinyin": "dazu",
    "real": "大足",
    "city_id": "500111"
  }, {
    "pinyin": "dean",
    "real": "德安",
    "city_id": "360426"
  }, {
    "pinyin": "dehuaxian",
    "real": "德化县",
    "city_id": "350526"
  }, {
    "pinyin": "dehuishi",
    "real": "德惠市",
    "city_id": "220183"
  }, {
    "pinyin": "dengfengshi",
    "real": "登封市",
    "city_id": "410185"
  }, {
    "pinyin": "dengta",
    "real": "灯塔",
    "city_id": "211081"
  }, {
    "pinyin": "dengzhoushi",
    "real": "邓州市",
    "city_id": "411381"
  }, {
    "pinyin": "deqing",
    "real": "德庆",
    "city_id": "441226"
  }, {
    "pinyin": "deqingxian",
    "real": "德清县",
    "city_id": "330521"
  }, {
    "pinyin": "dexing",
    "real": "德兴",
    "city_id": "361181"
  }, {
    "pinyin": "deyang",
    "real": "德阳",
    "city_id": "510600"
  }, {
    "pinyin": "dezhou",
    "real": "德州",
    "city_id": "371400"
  }, {
    "pinyin": "dianjiangxian",
    "real": "垫江县",
    "city_id": "500231"
  }, {
    "pinyin": "diaobingshanshi",
    "real": "调兵山市",
    "city_id": "211281"
  }, {
    "pinyin": "dingbian",
    "real": "定边",
    "city_id": "610825"
  }, {
    "pinyin": "dingxiang",
    "real": "定襄",
    "city_id": "140921"
  }, {
    "pinyin": "dingxing",
    "real": "定兴",
    "city_id": "130626"
  }, {
    "pinyin": "dingyuanxian",
    "real": "定远县",
    "city_id": "341125"
  }, {
    "pinyin": "dingzhoushi",
    "real": "定州市",
    "city_id": "130682"
  }, {
    "pinyin": "donga",
    "real": "东阿",
    "city_id": "371524"
  }, {
    "pinyin": "dongfang",
    "real": "东方",
    "city_id": "469007"
  }, {
    "pinyin": "dongfeng",
    "real": "东丰",
    "city_id": "220421"
  }, {
    "pinyin": "donggangshi",
    "real": "东港市",
    "city_id": "210681"
  }, {
    "pinyin": "dongguan",
    "real": "东莞",
    "city_id": "441900"
  }, {
    "pinyin": "dongguang",
    "real": "东光",
    "city_id": "130923"
  }, {
    "pinyin": "donghaixian",
    "real": "东海县",
    "city_id": "320722"
  }, {
    "pinyin": "dongkouxian",
    "real": "洞口县",
    "city_id": "430525"
  }, {
    "pinyin": "dongmingxian",
    "real": "东明县",
    "city_id": "371728"
  }, {
    "pinyin": "dongpingxian",
    "real": "东平县",
    "city_id": "370923"
  }, {
    "pinyin": "dongtaishi",
    "real": "东台市",
    "city_id": "320981"
  }, {
    "pinyin": "dongxiangxian",
    "real": "东乡县",
    "city_id": "361029"
  }, {
    "pinyin": "dongxing",
    "real": "东兴",
    "city_id": "450681"
  }, {
    "pinyin": "dongyang",
    "real": "东阳",
    "city_id": "330783"
  }, {
    "pinyin": "dongying",
    "real": "东营",
    "city_id": "370500"
  }, {
    "pinyin": "douchangxian",
    "real": "都昌县",
    "city_id": "360428"
  }, {
    "pinyin": "doujiangyanshi",
    "real": "都江堰市",
    "city_id": "510181"
  }, {
    "pinyin": "dunhuang",
    "real": "敦煌",
    "city_id": "620982"
  }, {
    "pinyin": "dunhuashi",
    "real": "敦化市",
    "city_id": "222403"
  }, {
    "pinyin": "duyunshi",
    "real": "都匀市",
    "city_id": "522701"
  }, {
    "pinyin": "shanxian",
    "real": "单县",
    "city_id": "371722"
  }],
  [{
    "pinyin": "eerduosi",
    "real": "鄂尔多斯",
    "city_id": "150600"
  }, {
    "pinyin": "eerguna",
    "real": "额尔古纳",
    "city_id": "150784"
  }, {
    "pinyin": "enpingshi",
    "real": "恩平市",
    "city_id": "440785"
  }, {
    "pinyin": "enshitujiazumiaozuzizhizhou",
    "real": "恩施土家族苗族自治州",
    "city_id": "422800"
  }, {
    "pinyin": "ezhou",
    "real": "鄂州",
    "city_id": "420700"
  }],
  [{
    "pinyin": "faku",
    "real": "法库",
    "city_id": "210124"
  }, {
    "pinyin": "fanchang",
    "real": "繁昌",
    "city_id": "340222"
  }, {
    "pinyin": "fangchenggang",
    "real": "防城港",
    "city_id": "450600"
  }, {
    "pinyin": "fangchengxian",
    "real": "方城县",
    "city_id": "411322"
  }, {
    "pinyin": "fanxian",
    "real": "范县",
    "city_id": "410926"
  }, {
    "pinyin": "fanzhi",
    "real": "繁峙",
    "city_id": "140924"
  }, {
    "pinyin": "feichengshi",
    "real": "肥城市",
    "city_id": "370983"
  }, {
    "pinyin": "feidongxian",
    "real": "肥东县",
    "city_id": "340122"
  }, {
    "pinyin": "feixian",
    "real": "费县",
    "city_id": "371325"
  }, {
    "pinyin": "feixiang",
    "real": "肥乡",
    "city_id": "130428"
  }, {
    "pinyin": "feixixian",
    "real": "肥西县",
    "city_id": "340123"
  }, {
    "pinyin": "fengchengshi",
    "real": "丰城市",
    "city_id": "360981"
  }, {
    "pinyin": "fengchengshi",
    "real": "凤城市",
    "city_id": "210682"
  }, {
    "pinyin": "fengdouxian",
    "real": "丰都县",
    "city_id": "500230"
  }, {
    "pinyin": "fenghuang",
    "real": "凤凰",
    "city_id": "433123"
  }, {
    "pinyin": "fenghuashi",
    "real": "奉化市",
    "city_id": "330283"
  }, {
    "pinyin": "fengjiexian",
    "real": "奉节县",
    "city_id": "500236"
  }, {
    "pinyin": "fengningmanzuzizhixian",
    "real": "丰宁满族自治县",
    "city_id": "130826"
  }, {
    "pinyin": "fengqiuxian",
    "real": "封丘县",
    "city_id": "410727"
  }, {
    "pinyin": "fengshun",
    "real": "丰顺",
    "city_id": "441423"
  }, {
    "pinyin": "fengtaixian",
    "real": "凤台县",
    "city_id": "340421"
  }, {
    "pinyin": "fengxian",
    "real": "丰县",
    "city_id": "320321"
  }, {
    "pinyin": "fengxin",
    "real": "奉新",
    "city_id": "360921"
  }, {
    "pinyin": "fengyangxian",
    "real": "凤阳县",
    "city_id": "341126"
  }, {
    "pinyin": "fenyang",
    "real": "汾阳",
    "city_id": "141182"
  }, {
    "pinyin": "fenyi",
    "real": "分宜",
    "city_id": "360521"
  }, {
    "pinyin": "fogang",
    "real": "佛冈",
    "city_id": "441821"
  }, {
    "pinyin": "foshan",
    "real": "佛山",
    "city_id": "440600"
  }, {
    "pinyin": "fuanshi",
    "real": "福安市",
    "city_id": "350981"
  }, {
    "pinyin": "fudingshi",
    "real": "福鼎市",
    "city_id": "350982"
  }, {
    "pinyin": "fugouxian",
    "real": "扶沟县",
    "city_id": "411621"
  }, {
    "pinyin": "funanxian",
    "real": "阜南县",
    "city_id": "341225"
  }, {
    "pinyin": "funingxian",
    "real": "阜宁县",
    "city_id": "320923"
  }, {
    "pinyin": "fuping",
    "real": "富平",
    "city_id": "610528"
  }, {
    "pinyin": "fushun",
    "real": "抚顺",
    "city_id": "210400"
  }, {
    "pinyin": "fushunxian",
    "real": "富顺县",
    "city_id": "510322"
  }, {
    "pinyin": "fusui",
    "real": "扶绥",
    "city_id": "451421"
  }, {
    "pinyin": "fuxin",
    "real": "阜新",
    "city_id": "210900"
  }, {
    "pinyin": "fuyang",
    "real": "阜阳",
    "city_id": "341200"
  }, {
    "pinyin": "fuyuanxian",
    "real": "富源县",
    "city_id": "530325"
  }, {
    "pinyin": "fuyuxian",
    "real": "扶余县",
    "city_id": "220724"
  }, {
    "pinyin": "fuzhou",
    "real": "福州",
    "city_id": "350100"
  }, {
    "pinyin": "fuzhou",
    "real": "抚州",
    "city_id": "361000"
  }],
  [{
    "pinyin": "gaizhoushi",
    "real": "盖州市",
    "city_id": "210881"
  }, {
    "pinyin": "ganxian",
    "real": "赣县",
    "city_id": "360721"
  }, {
    "pinyin": "ganyuxian",
    "real": "赣榆县",
    "city_id": "320721"
  }, {
    "pinyin": "ganzhou",
    "real": "赣州",
    "city_id": "360700"
  }, {
    "pinyin": "gaoanshi",
    "real": "高安市",
    "city_id": "360983"
  }, {
    "pinyin": "gaobeidianshi",
    "real": "高碑店市",
    "city_id": "130684"
  }, {
    "pinyin": "gaoling",
    "real": "高陵",
    "city_id": "610126"
  }, {
    "pinyin": "gaomishi",
    "real": "高密市",
    "city_id": "370785"
  }, {
    "pinyin": "gaopingshi",
    "real": "高平市",
    "city_id": "140581"
  }, {
    "pinyin": "gaotangxian",
    "real": "高唐县",
    "city_id": "371526"
  }, {
    "pinyin": "gaoyoushi",
    "real": "高邮市",
    "city_id": "321084"
  }, {
    "pinyin": "gaozhoushi",
    "real": "高州市",
    "city_id": "440981"
  }, {
    "pinyin": "gejiushi",
    "real": "个旧市",
    "city_id": "532501"
  }, {
    "pinyin": "gonganxian",
    "real": "公安县",
    "city_id": "421022"
  }, {
    "pinyin": "gongqingcheng",
    "real": "共青城",
    "city_id": "360482"
  }, {
    "pinyin": "gongyishi",
    "real": "巩义市",
    "city_id": "410181"
  }, {
    "pinyin": "gongzhulingshi",
    "real": "公主岭市",
    "city_id": "220381"
  }, {
    "pinyin": "guangan",
    "real": "广安",
    "city_id": "511600"
  }, {
    "pinyin": "guangdexian",
    "real": "广德县",
    "city_id": "341822"
  }, {
    "pinyin": "guangraoxian",
    "real": "广饶县",
    "city_id": "370523"
  }, {
    "pinyin": "guangshanxian",
    "real": "光山县",
    "city_id": "411522"
  }, {
    "pinyin": "guangshuishi",
    "real": "广水市",
    "city_id": "421381"
  }, {
    "pinyin": "guangyuan",
    "real": "广元",
    "city_id": "510800"
  }, {
    "pinyin": "guangzhou",
    "real": "广州",
    "city_id": "440100"
  }, {
    "pinyin": "guannanxian",
    "real": "灌南县",
    "city_id": "320724"
  }, {
    "pinyin": "guanxian",
    "real": "冠县",
    "city_id": "371525"
  }, {
    "pinyin": "guanxian",
    "real": "固安县",
    "city_id": "131022"
  }, {
    "pinyin": "guanyunxian",
    "real": "灌云县",
    "city_id": "320723"
  }, {
    "pinyin": "gucheng",
    "real": "故城",
    "city_id": "131126"
  }, {
    "pinyin": "guchengxian",
    "real": "谷城县",
    "city_id": "420625"
  }, {
    "pinyin": "guidong",
    "real": "桂东",
    "city_id": "431027"
  }, {
    "pinyin": "guigang",
    "real": "贵港",
    "city_id": "450800"
  }, {
    "pinyin": "guilin",
    "real": "桂林",
    "city_id": "450300"
  }, {
    "pinyin": "guipingshi",
    "real": "桂平市",
    "city_id": "450881"
  }, {
    "pinyin": "guixishi",
    "real": "贵溪市",
    "city_id": "360681"
  }, {
    "pinyin": "guiyang",
    "real": "贵阳",
    "city_id": "520100"
  }, {
    "pinyin": "guiyangxian",
    "real": "桂阳县",
    "city_id": "431021"
  }, {
    "pinyin": "gulin",
    "real": "古蔺",
    "city_id": "510525"
  }, {
    "pinyin": "gushixian",
    "real": "固始县",
    "city_id": "411525"
  }, {
    "pinyin": "gutian",
    "real": "古田",
    "city_id": "350922"
  }, {
    "pinyin": "guyuan",
    "real": "沽源",
    "city_id": "130724"
  }, {
    "pinyin": "guzhen",
    "real": "固镇",
    "city_id": "340323"
  }],
  [{
    "pinyin": "haerbin",
    "real": "哈尔滨",
    "city_id": "230100"
  }, {
    "pinyin": "haianxian",
    "real": "海安县",
    "city_id": "320621"
  }, {
    "pinyin": "haichengshi",
    "real": "海城市",
    "city_id": "210381"
  }, {
    "pinyin": "haifengxian",
    "real": "海丰县",
    "city_id": "441521"
  }, {
    "pinyin": "haikou",
    "real": "海口",
    "city_id": "460100"
  }, {
    "pinyin": "hailun",
    "real": "海伦",
    "city_id": "231283"
  }, {
    "pinyin": "haimenshi",
    "real": "海门市",
    "city_id": "320684"
  }, {
    "pinyin": "hainingshi",
    "real": "海宁市",
    "city_id": "330481"
  }, {
    "pinyin": "haiyangshi",
    "real": "海阳市",
    "city_id": "370687"
  }, {
    "pinyin": "haiyanxian",
    "real": "海盐县",
    "city_id": "330424"
  }, {
    "pinyin": "hamishi",
    "real": "哈密市",
    "city_id": "652201"
  }, {
    "pinyin": "hancheng",
    "real": "韩城",
    "city_id": "610581"
  }, {
    "pinyin": "hanchuanshi",
    "real": "汉川市",
    "city_id": "420984"
  }, {
    "pinyin": "handan",
    "real": "邯郸",
    "city_id": "130400"
  }, {
    "pinyin": "hangjinhouqi",
    "real": "杭锦后旗",
    "city_id": "150826"
  }, {
    "pinyin": "hangzhou",
    "real": "杭州",
    "city_id": "330100"
  }, {
    "pinyin": "hannan",
    "real": "汉南",
    "city_id": "420113"
  }, {
    "pinyin": "hanshouxian",
    "real": "汉寿县",
    "city_id": "430722"
  }, {
    "pinyin": "hanzhong",
    "real": "汉中",
    "city_id": "610700"
  }, {
    "pinyin": "hebi",
    "real": "鹤壁",
    "city_id": "410600"
  }, {
    "pinyin": "hefei",
    "real": "合肥",
    "city_id": "340100"
  }, {
    "pinyin": "heishanxian",
    "real": "黑山县",
    "city_id": "210726"
  }, {
    "pinyin": "hejiangxian",
    "real": "合江县",
    "city_id": "510522"
  }, {
    "pinyin": "hejianshi",
    "real": "河间市",
    "city_id": "130984"
  }, {
    "pinyin": "hejinshi",
    "real": "河津市",
    "city_id": "140882"
  }, {
    "pinyin": "hekouyaozuzizhixian",
    "real": "河口瑶族自治县",
    "city_id": "532532"
  }, {
    "pinyin": "helingeer",
    "real": "和林格尔",
    "city_id": "150123"
  }, {
    "pinyin": "hengdongxian",
    "real": "衡东县",
    "city_id": "430424"
  }, {
    "pinyin": "hengshan",
    "real": "衡山",
    "city_id": "430423"
  }, {
    "pinyin": "hengshui",
    "real": "衡水",
    "city_id": "131100"
  }, {
    "pinyin": "hengyang",
    "real": "衡阳",
    "city_id": "430400"
  }, {
    "pinyin": "hengyangxian",
    "real": "衡阳县",
    "city_id": "430421"
  }, {
    "pinyin": "heshanshi",
    "real": "鹤山市",
    "city_id": "440784"
  }, {
    "pinyin": "hetian",
    "real": "和田",
    "city_id": "653201"
  }, {
    "pinyin": "heyuan",
    "real": "河源",
    "city_id": "441600"
  }, {
    "pinyin": "heze",
    "real": "菏泽",
    "city_id": "371700"
  }, {
    "pinyin": "hezhou",
    "real": "贺州",
    "city_id": "451100"
  }, {
    "pinyin": "honganxian",
    "real": "红安县",
    "city_id": "421122"
  }, {
    "pinyin": "honghezhou",
    "real": "红河州",
    "city_id": "532500"
  }, {
    "pinyin": "honghushi",
    "real": "洪湖市",
    "city_id": "421083"
  }, {
    "pinyin": "hongya",
    "real": "洪雅",
    "city_id": "511423"
  }, {
    "pinyin": "hongze",
    "real": "洪泽",
    "city_id": "320829"
  }, {
    "pinyin": "houma",
    "real": "侯马",
    "city_id": "141081"
  }, {
    "pinyin": "huachuan",
    "real": "桦川",
    "city_id": "230826"
  }, {
    "pinyin": "huadianshi",
    "real": "桦甸市",
    "city_id": "220282"
  }, {
    "pinyin": "huaian",
    "real": "淮安",
    "city_id": "320800"
  }, {
    "pinyin": "huaibei",
    "real": "淮北",
    "city_id": "340600"
  }, {
    "pinyin": "huaibinxian",
    "real": "淮滨县",
    "city_id": "411527"
  }, {
    "pinyin": "huaihua",
    "real": "怀化",
    "city_id": "431200"
  }, {
    "pinyin": "huaiji",
    "real": "怀集",
    "city_id": "441224"
  }, {
    "pinyin": "huailai",
    "real": "怀来",
    "city_id": "130730"
  }, {
    "pinyin": "huainan",
    "real": "淮南",
    "city_id": "340400"
  }, {
    "pinyin": "huairen",
    "real": "怀仁",
    "city_id": "140624"
  }, {
    "pinyin": "huairou",
    "real": "怀柔",
    "city_id": "110116"
  }, {
    "pinyin": "huaiyangxian",
    "real": "淮阳县",
    "city_id": "411626"
  }, {
    "pinyin": "huangchuanxian",
    "real": "潢川县",
    "city_id": "411526"
  }, {
    "pinyin": "huanggang",
    "real": "黄冈",
    "city_id": "421100"
  }, {
    "pinyin": "huanghua",
    "real": "黄骅",
    "city_id": "130983"
  }, {
    "pinyin": "huangmeixian",
    "real": "黄梅县",
    "city_id": "421127"
  }, {
    "pinyin": "huangpo",
    "real": "黄陂",
    "city_id": "420116"
  }, {
    "pinyin": "huangshan",
    "real": "黄山",
    "city_id": "341000"
  }, {
    "pinyin": "huangshi",
    "real": "黄石",
    "city_id": "420200"
  }, {
    "pinyin": "huantaixian",
    "real": "桓台县",
    "city_id": "370321"
  }, {
    "pinyin": "huarongxian",
    "real": "华容县",
    "city_id": "430623"
  }, {
    "pinyin": "huaxian",
    "real": "滑县",
    "city_id": "410526"
  }, {
    "pinyin": "huaying",
    "real": "华蓥",
    "city_id": "511681"
  }, {
    "pinyin": "huayuan",
    "real": "花垣",
    "city_id": "433124"
  }, {
    "pinyin": "huazhoushi",
    "real": "化州市",
    "city_id": "440982"
  }, {
    "pinyin": "huhehaote",
    "real": "呼和浩特",
    "city_id": "150100"
  }, {
    "pinyin": "huianxian",
    "real": "惠安县",
    "city_id": "350521"
  }, {
    "pinyin": "huichangxian",
    "real": "会昌县",
    "city_id": "360733"
  }, {
    "pinyin": "huidongxian",
    "real": "惠东县",
    "city_id": "441323"
  }, {
    "pinyin": "huili",
    "real": "会理",
    "city_id": "513425"
  }, {
    "pinyin": "huinanxian",
    "real": "辉南县",
    "city_id": "220523"
  }, {
    "pinyin": "huixianshi",
    "real": "辉县市",
    "city_id": "410782"
  }, {
    "pinyin": "huizhou",
    "real": "惠州",
    "city_id": "441300"
  }, {
    "pinyin": "hukou",
    "real": "湖口",
    "city_id": "360429"
  }, {
    "pinyin": "huludao",
    "real": "葫芦岛",
    "city_id": "211400"
  }, {
    "pinyin": "hulunbeier",
    "real": "呼伦贝尔",
    "city_id": "150700"
  }, {
    "pinyin": "hunchunshi",
    "real": "珲春市",
    "city_id": "222404"
  }, {
    "pinyin": "huojia",
    "real": "获嘉",
    "city_id": "410724"
  }, {
    "pinyin": "huojugaojishuchanyekaifaqu",
    "real": "火炬高技术产业开发区",
    "city_id": "4420005"
  }, {
    "pinyin": "huolinguole",
    "real": "霍林郭勒",
    "city_id": "150581"
  }, {
    "pinyin": "huoqiuxian",
    "real": "霍邱县",
    "city_id": "341522"
  }, {
    "pinyin": "huozhou",
    "real": "霍州",
    "city_id": "141082"
  }, {
    "pinyin": "huxian",
    "real": "户县",
    "city_id": "610125"
  }, {
    "pinyin": "huzhou",
    "real": "湖州",
    "city_id": "330500"
  }],
  [

  ],
  [{
    "pinyin": "jiahe",
    "real": "嘉禾",
    "city_id": "431024"
  }, {
    "pinyin": "jiajiang",
    "real": "夹江",
    "city_id": "511126"
  }, {
    "pinyin": "jiamusi",
    "real": "佳木斯",
    "city_id": "230800"
  }, {
    "pinyin": "jian",
    "real": "吉安",
    "city_id": "360800"
  }, {
    "pinyin": "jian",
    "real": "集安",
    "city_id": "220582"
  }, {
    "pinyin": "jianchang",
    "real": "建昌",
    "city_id": "211422"
  }, {
    "pinyin": "jiandeshi",
    "real": "建德市",
    "city_id": "330182"
  }, {
    "pinyin": "jiangdushi",
    "real": "江都市",
    "city_id": "321012"
  }, {
    "pinyin": "jiange",
    "real": "剑阁",
    "city_id": "510823"
  }, {
    "pinyin": "jianghuayaozuzizhixian",
    "real": "江华瑶族自治县",
    "city_id": "431129"
  }, {
    "pinyin": "jiangmen",
    "real": "江门",
    "city_id": "440700"
  }, {
    "pinyin": "jiangshanshi",
    "real": "江山市",
    "city_id": "330881"
  }, {
    "pinyin": "jiangxian",
    "real": "绛县",
    "city_id": "140826"
  }, {
    "pinyin": "jiangyanshi",
    "real": "姜堰市",
    "city_id": "321284"
  }, {
    "pinyin": "jiangyoushi",
    "real": "江油市",
    "city_id": "510781"
  }, {
    "pinyin": "jianhuxian",
    "real": "建湖县",
    "city_id": "320925"
  }, {
    "pinyin": "jianlixian",
    "real": "监利县",
    "city_id": "421023"
  }, {
    "pinyin": "jianoushi",
    "real": "建瓯市",
    "city_id": "350783"
  }, {
    "pinyin": "jianshi",
    "real": "建始",
    "city_id": "422822"
  }, {
    "pinyin": "jianshuixian",
    "real": "建水县",
    "city_id": "532524"
  }, {
    "pinyin": "jianwei",
    "real": "犍为",
    "city_id": "511123"
  }, {
    "pinyin": "jianxian",
    "real": "吉安县",
    "city_id": "360821"
  }, {
    "pinyin": "jianyangshi",
    "real": "简阳市",
    "city_id": "512081"
  }, {
    "pinyin": "jiaocheng",
    "real": "交城",
    "city_id": "141122"
  }, {
    "pinyin": "jiaoheshi",
    "real": "蛟河市",
    "city_id": "220281"
  }, {
    "pinyin": "jiaonanshi",
    "real": "胶南市",
    "city_id": "370284"
  }, {
    "pinyin": "jiaozhoushi",
    "real": "胶州市",
    "city_id": "370281"
  }, {
    "pinyin": "jiaozuo",
    "real": "焦作",
    "city_id": "410800"
  }, {
    "pinyin": "jiashanxian",
    "real": "嘉善县",
    "city_id": "330421"
  }, {
    "pinyin": "jiaxian",
    "real": "郏县",
    "city_id": "410425"
  }, {
    "pinyin": "jiaxiangxian",
    "real": "嘉祥县",
    "city_id": "370829"
  }, {
    "pinyin": "jiaxing",
    "real": "嘉兴",
    "city_id": "330400"
  }, {
    "pinyin": "jiayu",
    "real": "嘉鱼",
    "city_id": "421221"
  }, {
    "pinyin": "jiayuguan",
    "real": "嘉峪关",
    "city_id": "620200"
  }, {
    "pinyin": "jidong",
    "real": "鸡东",
    "city_id": "230321"
  }, {
    "pinyin": "jieshoushi",
    "real": "界首市",
    "city_id": "341282"
  }, {
    "pinyin": "jiexiushi",
    "real": "介休市",
    "city_id": "140781"
  }, {
    "pinyin": "jieyang",
    "real": "揭阳",
    "city_id": "445200"
  }, {
    "pinyin": "jili",
    "real": "吉利",
    "city_id": "410306"
  }, {
    "pinyin": "jilin",
    "real": "吉林",
    "city_id": "220200"
  }, {
    "pinyin": "jinan",
    "real": "济南",
    "city_id": "370100"
  }, {
    "pinyin": "jincheng",
    "real": "晋城",
    "city_id": "140500"
  }, {
    "pinyin": "jingdezhen",
    "real": "景德镇",
    "city_id": "360200"
  }, {
    "pinyin": "jinghongshi",
    "real": "景洪市",
    "city_id": "532801"
  }, {
    "pinyin": "jingjiangshi",
    "real": "靖江市",
    "city_id": "321282"
  }, {
    "pinyin": "jingmen",
    "real": "荆门",
    "city_id": "420800"
  }, {
    "pinyin": "jingshanxian",
    "real": "京山县",
    "city_id": "420821"
  }, {
    "pinyin": "jingtai",
    "real": "景泰",
    "city_id": "620423"
  }, {
    "pinyin": "jingxian",
    "real": "泾县",
    "city_id": "341823"
  }, {
    "pinyin": "jingyang",
    "real": "泾阳",
    "city_id": "610423"
  }, {
    "pinyin": "jingyu",
    "real": "靖宇",
    "city_id": "220622"
  }, {
    "pinyin": "jingzhou",
    "real": "荆州",
    "city_id": "421000"
  }, {
    "pinyin": "jinhua",
    "real": "金华",
    "city_id": "330700"
  }, {
    "pinyin": "jinhuxian",
    "real": "金湖县",
    "city_id": "320831"
  }, {
    "pinyin": "jining",
    "real": "济宁",
    "city_id": "370800"
  }, {
    "pinyin": "jinjiang",
    "real": "晋江",
    "city_id": "350582"
  }, {
    "pinyin": "jinning",
    "real": "晋宁",
    "city_id": "530122"
  }, {
    "pinyin": "jinshaxian",
    "real": "金沙县",
    "city_id": "520523"
  }, {
    "pinyin": "jintangxian",
    "real": "金堂县",
    "city_id": "510121"
  }, {
    "pinyin": "jintanshi",
    "real": "金坛市",
    "city_id": "320482"
  }, {
    "pinyin": "jinxiangxian",
    "real": "金乡县",
    "city_id": "370828"
  }, {
    "pinyin": "jinxianxian",
    "real": "进贤县",
    "city_id": "360124"
  }, {
    "pinyin": "jinyunxian",
    "real": "缙云县",
    "city_id": "331122"
  }, {
    "pinyin": "jinzhai",
    "real": "金寨",
    "city_id": "341524"
  }, {
    "pinyin": "jinzhong",
    "real": "晋中",
    "city_id": "140700"
  }, {
    "pinyin": "jinzhou",
    "real": "锦州",
    "city_id": "210700"
  }, {
    "pinyin": "jinzhou",
    "real": "晋州",
    "city_id": "130183"
  }, {
    "pinyin": "jishou",
    "real": "吉首",
    "city_id": "433101"
  }, {
    "pinyin": "jishuixian",
    "real": "吉水县",
    "city_id": "360822"
  }, {
    "pinyin": "jiujiang",
    "real": "九江",
    "city_id": "360400"
  }, {
    "pinyin": "jiuquan",
    "real": "酒泉",
    "city_id": "620900"
  }, {
    "pinyin": "jiutaishi",
    "real": "九台市",
    "city_id": "220181"
  }, {
    "pinyin": "jixi",
    "real": "鸡西",
    "city_id": "230300"
  }, {
    "pinyin": "jixian",
    "real": "蓟县",
    "city_id": "120225"
  }, {
    "pinyin": "jiyuan",
    "real": "济源",
    "city_id": "419001"
  }, {
    "pinyin": "jizhou",
    "real": "冀州",
    "city_id": "131181"
  }, {
    "pinyin": "juanchengxian",
    "real": "鄄城县",
    "city_id": "371726"
  }, {
    "pinyin": "junanxian",
    "real": "莒南县",
    "city_id": "371327"
  }, {
    "pinyin": "jurong",
    "real": "句容",
    "city_id": "321183"
  }, {
    "pinyin": "juxian",
    "real": "莒县",
    "city_id": "371122"
  }, {
    "pinyin": "juyexian",
    "real": "巨野县",
    "city_id": "371724"
  }],
  [{
    "pinyin": "kaifeng",
    "real": "开封",
    "city_id": "410200"
  }, {
    "pinyin": "kaihua",
    "real": "开化",
    "city_id": "330824"
  }, {
    "pinyin": "kaili",
    "real": "凯里",
    "city_id": "522601"
  }, {
    "pinyin": "kailu",
    "real": "开鲁",
    "city_id": "150523"
  }, {
    "pinyin": "kaixian",
    "real": "开县",
    "city_id": "500234"
  }, {
    "pinyin": "kaiyuanshi",
    "real": "开原市",
    "city_id": "211282"
  }, {
    "pinyin": "kaiyuanshi",
    "real": "开远市",
    "city_id": "532502"
  }, {
    "pinyin": "kangding",
    "real": "康定",
    "city_id": "513321"
  }, {
    "pinyin": "keerqinyouyiqianqi",
    "real": "科尔沁右翼前旗",
    "city_id": "152221"
  }, {
    "pinyin": "keerqinyouyizhongqi",
    "real": "科尔沁右翼中旗",
    "city_id": "152222"
  }, {
    "pinyin": "keerqinzuoyihouqi",
    "real": "科尔沁左翼后旗",
    "city_id": "150522"
  }, {
    "pinyin": "kelamayi",
    "real": "克拉玛依",
    "city_id": "650200"
  }, {
    "pinyin": "kenli",
    "real": "垦利",
    "city_id": "370521"
  }, {
    "pinyin": "keshan",
    "real": "克山",
    "city_id": "230229"
  }, {
    "pinyin": "kuanchengmanzuzizhixian",
    "real": "宽城满族自治县",
    "city_id": "130827"
  }, {
    "pinyin": "kuerle",
    "real": "库尔勒",
    "city_id": "652801"
  }, {
    "pinyin": "kuitun",
    "real": "奎屯",
    "city_id": "654003"
  }, {
    "pinyin": "kunming",
    "real": "昆明",
    "city_id": "530100"
  }, {
    "pinyin": "kunshan",
    "real": "昆山",
    "city_id": "320583"
  }],
  [{
    "pinyin": "laifeng",
    "real": "来凤",
    "city_id": "422827"
  }, {
    "pinyin": "laishui",
    "real": "涞水",
    "city_id": "130623"
  }, {
    "pinyin": "laiwu",
    "real": "莱芜",
    "city_id": "371200"
  }, {
    "pinyin": "laixishi",
    "real": "莱西市",
    "city_id": "370285"
  }, {
    "pinyin": "laiyangshi",
    "real": "莱阳市",
    "city_id": "370682"
  }, {
    "pinyin": "laizhoushi",
    "real": "莱州市",
    "city_id": "370683"
  }, {
    "pinyin": "langfang",
    "real": "廊坊",
    "city_id": "131000"
  }, {
    "pinyin": "langxi",
    "real": "郎溪",
    "city_id": "341821"
  }, {
    "pinyin": "langzhongshi",
    "real": "阆中市",
    "city_id": "511381"
  }, {
    "pinyin": "lankaoxian",
    "real": "兰考县",
    "city_id": "410225"
  }, {
    "pinyin": "lanlingxian",
    "real": "兰陵县",
    "city_id": "371324"
  }, {
    "pinyin": "lanxi",
    "real": "兰西",
    "city_id": "231222"
  }, {
    "pinyin": "lanxishi",
    "real": "兰溪市",
    "city_id": "330781"
  }, {
    "pinyin": "lanzhou",
    "real": "兰州",
    "city_id": "620100"
  }, {
    "pinyin": "laohekoushi",
    "real": "老河口市",
    "city_id": "420682"
  }, {
    "pinyin": "lasa",
    "real": "拉萨",
    "city_id": "540100"
  }, {
    "pinyin": "lechang",
    "real": "乐昌",
    "city_id": "440281"
  }, {
    "pinyin": "leiyangshi",
    "real": "耒阳市",
    "city_id": "430481"
  }, {
    "pinyin": "leizhoushi",
    "real": "雷州市",
    "city_id": "440882"
  }, {
    "pinyin": "lelingshi",
    "real": "乐陵市",
    "city_id": "371481"
  }, {
    "pinyin": "lengshuijiangshi",
    "real": "冷水江市",
    "city_id": "431381"
  }, {
    "pinyin": "lepingshi",
    "real": "乐平市",
    "city_id": "360281"
  }, {
    "pinyin": "leshan",
    "real": "乐山",
    "city_id": "511100"
  }, {
    "pinyin": "lezhi",
    "real": "乐至",
    "city_id": "512022"
  }, {
    "pinyin": "liangpingxian",
    "real": "梁平县",
    "city_id": "500228"
  }, {
    "pinyin": "liangshanxian",
    "real": "梁山县",
    "city_id": "370832"
  }, {
    "pinyin": "lianjiangshi",
    "real": "廉江市",
    "city_id": "440881"
  }, {
    "pinyin": "lianjiangxian",
    "real": "连江县",
    "city_id": "350122"
  }, {
    "pinyin": "lianshuixian",
    "real": "涟水县",
    "city_id": "320826"
  }, {
    "pinyin": "lianyuanshi",
    "real": "涟源市",
    "city_id": "431382"
  }, {
    "pinyin": "lianyungang",
    "real": "连云港",
    "city_id": "320700"
  }, {
    "pinyin": "lianzhou",
    "real": "连州",
    "city_id": "441882"
  }, {
    "pinyin": "liaocheng",
    "real": "聊城",
    "city_id": "371500"
  }, {
    "pinyin": "liaoyang",
    "real": "辽阳",
    "city_id": "211000"
  }, {
    "pinyin": "liaoyangxian",
    "real": "辽阳县",
    "city_id": "211021"
  }, {
    "pinyin": "liaoyuan",
    "real": "辽源",
    "city_id": "220400"
  }, {
    "pinyin": "liaozhong",
    "real": "辽中",
    "city_id": "210122"
  }, {
    "pinyin": "lichuanshi",
    "real": "利川市",
    "city_id": "422802"
  }, {
    "pinyin": "lijiang",
    "real": "丽江",
    "city_id": "530700"
  }, {
    "pinyin": "lilingshi",
    "real": "醴陵市",
    "city_id": "430281"
  }, {
    "pinyin": "linan",
    "real": "临安",
    "city_id": "330185"
  }, {
    "pinyin": "lincang",
    "real": "临沧",
    "city_id": "530900"
  }, {
    "pinyin": "linfen",
    "real": "临汾",
    "city_id": "141000"
  }, {
    "pinyin": "lingaoxian",
    "real": "临高县",
    "city_id": "469024"
  }, {
    "pinyin": "lingbaoshi",
    "real": "灵宝市",
    "city_id": "411282"
  }, {
    "pinyin": "lingbixian",
    "real": "灵璧县",
    "city_id": "341323"
  }, {
    "pinyin": "lingchuan",
    "real": "灵川",
    "city_id": "450323"
  }, {
    "pinyin": "linghai",
    "real": "凌海",
    "city_id": "210781"
  }, {
    "pinyin": "lingshou",
    "real": "灵寿",
    "city_id": "130126"
  }, {
    "pinyin": "lingshuilizuzizhixian",
    "real": "陵水黎族自治县",
    "city_id": "469028"
  }, {
    "pinyin": "lingwu",
    "real": "灵武",
    "city_id": "640181"
  }, {
    "pinyin": "lingyuanshi",
    "real": "凌源市",
    "city_id": "211382"
  }, {
    "pinyin": "linhaishi",
    "real": "临海市",
    "city_id": "331082"
  }, {
    "pinyin": "linjiang",
    "real": "临江",
    "city_id": "220681"
  }, {
    "pinyin": "linquanxian",
    "real": "临泉县",
    "city_id": "341221"
  }, {
    "pinyin": "linquxian",
    "real": "临朐县",
    "city_id": "370724"
  }, {
    "pinyin": "linshuixian",
    "real": "邻水县",
    "city_id": "511623"
  }, {
    "pinyin": "linshuxian",
    "real": "临沭县",
    "city_id": "371329"
  }, {
    "pinyin": "linxi",
    "real": "林西",
    "city_id": "150424"
  }, {
    "pinyin": "linyi",
    "real": "临沂",
    "city_id": "371300"
  }, {
    "pinyin": "linyingxian",
    "real": "临颍县",
    "city_id": "411122"
  }, {
    "pinyin": "linyixian",
    "real": "临猗县",
    "city_id": "140821"
  }, {
    "pinyin": "linyixian",
    "real": "临邑县",
    "city_id": "371424"
  }, {
    "pinyin": "linzhoushi",
    "real": "林州市",
    "city_id": "410581"
  }, {
    "pinyin": "lishui",
    "real": "丽水",
    "city_id": "331100"
  }, {
    "pinyin": "lishuixian",
    "real": "溧水县",
    "city_id": "320124"
  }, {
    "pinyin": "lishuxian",
    "real": "梨树县",
    "city_id": "220322"
  }, {
    "pinyin": "liuhe",
    "real": "柳河",
    "city_id": "220524"
  }, {
    "pinyin": "liulin",
    "real": "柳林",
    "city_id": "141125"
  }, {
    "pinyin": "liupanshui",
    "real": "六盘水",
    "city_id": "520200"
  }, {
    "pinyin": "liuyangshi",
    "real": "浏阳市",
    "city_id": "430181"
  }, {
    "pinyin": "liuzhou",
    "real": "柳州",
    "city_id": "450200"
  }, {
    "pinyin": "lixian",
    "real": "澧县",
    "city_id": "430723"
  }, {
    "pinyin": "lixian",
    "real": "蠡县",
    "city_id": "130635"
  }, {
    "pinyin": "lixinxian",
    "real": "利辛县",
    "city_id": "341623"
  }, {
    "pinyin": "liyangshi",
    "real": "溧阳市",
    "city_id": "320481"
  }, {
    "pinyin": "longchangxian",
    "real": "隆昌县",
    "city_id": "511028"
  }, {
    "pinyin": "longchuan",
    "real": "龙川",
    "city_id": "441622"
  }, {
    "pinyin": "longhua",
    "real": "隆化",
    "city_id": "130825"
  }, {
    "pinyin": "longhuixian",
    "real": "隆回县",
    "city_id": "430524"
  }, {
    "pinyin": "longkoushi",
    "real": "龙口市",
    "city_id": "370681"
  }, {
    "pinyin": "longnanxian",
    "real": "龙南县",
    "city_id": "360727"
  }, {
    "pinyin": "longquanshi",
    "real": "龙泉市",
    "city_id": "331181"
  }, {
    "pinyin": "longshanxian",
    "real": "龙山县",
    "city_id": "433130"
  }, {
    "pinyin": "longyan",
    "real": "龙岩",
    "city_id": "350800"
  }, {
    "pinyin": "longyouxian",
    "real": "龙游县",
    "city_id": "330825"
  }, {
    "pinyin": "loudi",
    "real": "娄底",
    "city_id": "431300"
  }, {
    "pinyin": "luan",
    "real": "六安",
    "city_id": "341500"
  }, {
    "pinyin": "luancheng",
    "real": "栾城",
    "city_id": "130124"
  }, {
    "pinyin": "luanchuan",
    "real": "栾川",
    "city_id": "410324"
  }, {
    "pinyin": "luannanxian",
    "real": "滦南县",
    "city_id": "130224"
  }, {
    "pinyin": "luanxian",
    "real": "滦县",
    "city_id": "130223"
  }, {
    "pinyin": "lufengshi",
    "real": "陆丰市",
    "city_id": "441581"
  }, {
    "pinyin": "lujiangxian",
    "real": "庐江县",
    "city_id": "340124"
  }, {
    "pinyin": "luliangxian",
    "real": "陆良县",
    "city_id": "530322"
  }, {
    "pinyin": "luoding",
    "real": "罗定",
    "city_id": "445381"
  }, {
    "pinyin": "luohe",
    "real": "漯河",
    "city_id": "411100"
  }, {
    "pinyin": "luojiang",
    "real": "罗江",
    "city_id": "510626"
  }, {
    "pinyin": "luoning",
    "real": "洛宁",
    "city_id": "410328"
  }, {
    "pinyin": "luopingxian",
    "real": "罗平县",
    "city_id": "530324"
  }, {
    "pinyin": "luoshanxian",
    "real": "罗山县",
    "city_id": "411521"
  }, {
    "pinyin": "luotianxian",
    "real": "罗田县",
    "city_id": "421123"
  }, {
    "pinyin": "luoyang",
    "real": "洛阳",
    "city_id": "410300"
  }, {
    "pinyin": "luoyuan",
    "real": "罗源",
    "city_id": "350123"
  }, {
    "pinyin": "luquan",
    "real": "鹿泉",
    "city_id": "130185"
  }, {
    "pinyin": "lushanxian",
    "real": "鲁山县",
    "city_id": "410423"
  }, {
    "pinyin": "lushi",
    "real": "卢氏",
    "city_id": "411224"
  }, {
    "pinyin": "luxian",
    "real": "泸县",
    "city_id": "510521"
  }, {
    "pinyin": "luyixian",
    "real": "鹿邑县",
    "city_id": "411628"
  }, {
    "pinyin": "luzhai",
    "real": "鹿寨",
    "city_id": "450223"
  }, {
    "pinyin": "luzhou",
    "real": "泸州",
    "city_id": "510500"
  }, {
    "pinyin": "lvliang",
    "real": "吕梁",
    "city_id": "141100"
  }],
  [{
    "pinyin": "maanshan",
    "real": "马鞍山",
    "city_id": "340500"
  }, {
    "pinyin": "machengshi",
    "real": "麻城市",
    "city_id": "421181"
  }, {
    "pinyin": "maerkang",
    "real": "马尔康",
    "city_id": "513229"
  }, {
    "pinyin": "mancheng",
    "real": "满城",
    "city_id": "130621"
  }, {
    "pinyin": "mangshi",
    "real": "芒市",
    "city_id": "533103"
  }, {
    "pinyin": "manzhoulishi",
    "real": "满洲里市",
    "city_id": "150781"
  }, {
    "pinyin": "maoming",
    "real": "茂名",
    "city_id": "440900"
  }, {
    "pinyin": "mayong",
    "real": "麻涌",
    "city_id": "4419026"
  }, {
    "pinyin": "meihekoushi",
    "real": "梅河口市",
    "city_id": "220581"
  }, {
    "pinyin": "meishan",
    "real": "眉山",
    "city_id": "511400"
  }, {
    "pinyin": "meitan",
    "real": "湄潭",
    "city_id": "520328"
  }, {
    "pinyin": "meizhou",
    "real": "梅州",
    "city_id": "441400"
  }, {
    "pinyin": "mengchengxian",
    "real": "蒙城县",
    "city_id": "341622"
  }, {
    "pinyin": "mengjin",
    "real": "孟津",
    "city_id": "410322"
  }, {
    "pinyin": "mengyinxian",
    "real": "蒙阴县",
    "city_id": "371328"
  }, {
    "pinyin": "mengzhou",
    "real": "孟州",
    "city_id": "410883"
  }, {
    "pinyin": "mengzi",
    "real": "蒙自",
    "city_id": "532503"
  }, {
    "pinyin": "mianchi",
    "real": "渑池",
    "city_id": "411221"
  }, {
    "pinyin": "mianyang",
    "real": "绵阳",
    "city_id": "510700"
  }, {
    "pinyin": "mianzhushi",
    "real": "绵竹市",
    "city_id": "510683"
  }, {
    "pinyin": "milexian",
    "real": "弥勒县",
    "city_id": "532526"
  }, {
    "pinyin": "miluoshi",
    "real": "汨罗市",
    "city_id": "430681"
  }, {
    "pinyin": "minquanxian",
    "real": "民权县",
    "city_id": "411421"
  }, {
    "pinyin": "mishan",
    "real": "密山",
    "city_id": "230382"
  }, {
    "pinyin": "miyangxian",
    "real": "泌阳县",
    "city_id": "411726"
  }, {
    "pinyin": "miyunxian",
    "real": "密云县",
    "city_id": "110228"
  }, {
    "pinyin": "mudanjiang",
    "real": "牡丹江",
    "city_id": "231000"
  }],
  [{
    "pinyin": "naimanqi",
    "real": "奈曼旗",
    "city_id": "150525"
  }, {
    "pinyin": "nananshi",
    "real": "南安市",
    "city_id": "350583"
  }, {
    "pinyin": "nanbuxian",
    "real": "南部县",
    "city_id": "511321"
  }, {
    "pinyin": "nanchang",
    "real": "南昌",
    "city_id": "360100"
  }, {
    "pinyin": "nanchong",
    "real": "南充",
    "city_id": "511300"
  }, {
    "pinyin": "nanchuan",
    "real": "南川",
    "city_id": "500119"
  }, {
    "pinyin": "nangongshi",
    "real": "南宫市",
    "city_id": "130581"
  }, {
    "pinyin": "nanjiang",
    "real": "南江",
    "city_id": "511922"
  }, {
    "pinyin": "nanjing",
    "real": "南京",
    "city_id": "320100"
  }, {
    "pinyin": "nanle",
    "real": "南乐",
    "city_id": "410923"
  }, {
    "pinyin": "nanling",
    "real": "南陵",
    "city_id": "340223"
  }, {
    "pinyin": "nanning",
    "real": "南宁",
    "city_id": "450100"
  }, {
    "pinyin": "nanping",
    "real": "南平",
    "city_id": "350700"
  }, {
    "pinyin": "nantong",
    "real": "南通",
    "city_id": "320600"
  }, {
    "pinyin": "nanxi",
    "real": "南溪",
    "city_id": "511503"
  }, {
    "pinyin": "nanxian",
    "real": "南县",
    "city_id": "430921"
  }, {
    "pinyin": "nanxiong",
    "real": "南雄",
    "city_id": "440282"
  }, {
    "pinyin": "nanyang",
    "real": "南阳",
    "city_id": "411300"
  }, {
    "pinyin": "nanyue",
    "real": "南岳",
    "city_id": "430412"
  }, {
    "pinyin": "nanzhangxian",
    "real": "南漳县",
    "city_id": "420624"
  }, {
    "pinyin": "nanzhaoxian",
    "real": "南召县",
    "city_id": "411321"
  }, {
    "pinyin": "nanzheng",
    "real": "南郑",
    "city_id": "610721"
  }, {
    "pinyin": "neihuang",
    "real": "内黄",
    "city_id": "410527"
  }, {
    "pinyin": "neijiang",
    "real": "内江",
    "city_id": "511000"
  }, {
    "pinyin": "neixiangxian",
    "real": "内乡县",
    "city_id": "411325"
  }, {
    "pinyin": "ningbo",
    "real": "宁波",
    "city_id": "330200"
  }, {
    "pinyin": "ningcheng",
    "real": "宁城",
    "city_id": "150429"
  }, {
    "pinyin": "ningde",
    "real": "宁德",
    "city_id": "350900"
  }, {
    "pinyin": "ningdouxian",
    "real": "宁都县",
    "city_id": "360730"
  }, {
    "pinyin": "ningguoshi",
    "real": "宁国市",
    "city_id": "341881"
  }, {
    "pinyin": "ninghaixian",
    "real": "宁海县",
    "city_id": "330226"
  }, {
    "pinyin": "ninghexian",
    "real": "宁河县",
    "city_id": "120221"
  }, {
    "pinyin": "ningjin",
    "real": "宁津",
    "city_id": "371422"
  }, {
    "pinyin": "ningjinxian",
    "real": "宁晋县",
    "city_id": "130528"
  }, {
    "pinyin": "ningling",
    "real": "宁陵",
    "city_id": "411423"
  }, {
    "pinyin": "ningxiangxian",
    "real": "宁乡县",
    "city_id": "430124"
  }, {
    "pinyin": "ningyangxian",
    "real": "宁阳县",
    "city_id": "370921"
  }, {
    "pinyin": "ningyuanxian",
    "real": "宁远县",
    "city_id": "431126"
  }, {
    "pinyin": "nonganxian",
    "real": "农安县",
    "city_id": "220122"
  }],
  [

  ],
  [{
    "pinyin": "panan",
    "real": "磐安",
    "city_id": "330727"
  }, {
    "pinyin": "panjin",
    "real": "盘锦",
    "city_id": "211100"
  }, {
    "pinyin": "panshishi",
    "real": "磐石市",
    "city_id": "220284"
  }, {
    "pinyin": "panxian",
    "real": "盘县",
    "city_id": "520222"
  }, {
    "pinyin": "panzhihua",
    "real": "攀枝花",
    "city_id": "510400"
  }, {
    "pinyin": "peixian",
    "real": "沛县",
    "city_id": "320322"
  }, {
    "pinyin": "penganxian",
    "real": "蓬安县",
    "city_id": "511323"
  }, {
    "pinyin": "penglai",
    "real": "蓬莱",
    "city_id": "370684"
  }, {
    "pinyin": "pengshan",
    "real": "彭山",
    "city_id": "511422"
  }, {
    "pinyin": "pengshuimiaozutujiazuzizhixian",
    "real": "彭水苗族土家族自治县",
    "city_id": "500243"
  }, {
    "pinyin": "pengxi",
    "real": "蓬溪",
    "city_id": "510921"
  }, {
    "pinyin": "pengze",
    "real": "彭泽",
    "city_id": "360430"
  }, {
    "pinyin": "pengzhoushi",
    "real": "彭州市",
    "city_id": "510182"
  }, {
    "pinyin": "pingchangxian",
    "real": "平昌县",
    "city_id": "511923"
  }, {
    "pinyin": "pingdingshan",
    "real": "平顶山",
    "city_id": "410400"
  }, {
    "pinyin": "pingdushi",
    "real": "平度市",
    "city_id": "370283"
  }, {
    "pinyin": "pinggu",
    "real": "平谷",
    "city_id": "110117"
  }, {
    "pinyin": "pinghushi",
    "real": "平湖市",
    "city_id": "330482"
  }, {
    "pinyin": "pingjiangxian",
    "real": "平江县",
    "city_id": "430626"
  }, {
    "pinyin": "pingliang",
    "real": "平凉",
    "city_id": "620800"
  }, {
    "pinyin": "pinglu",
    "real": "平陆",
    "city_id": "140829"
  }, {
    "pinyin": "pingluo",
    "real": "平罗",
    "city_id": "640221"
  }, {
    "pinyin": "pingnanxian",
    "real": "平南县",
    "city_id": "450821"
  }, {
    "pinyin": "pingquan",
    "real": "平泉",
    "city_id": "130823"
  }, {
    "pinyin": "pingshan",
    "real": "平山",
    "city_id": "130131"
  }, {
    "pinyin": "pingtan",
    "real": "平潭",
    "city_id": "350128"
  }, {
    "pinyin": "pingxiang",
    "real": "萍乡",
    "city_id": "360300"
  }, {
    "pinyin": "pingxiang",
    "real": "平乡",
    "city_id": "130532"
  }, {
    "pinyin": "pingyangxian",
    "real": "平阳县",
    "city_id": "330326"
  }, {
    "pinyin": "pingyaoxian",
    "real": "平遥县",
    "city_id": "140728"
  }, {
    "pinyin": "pingyixian",
    "real": "平邑县",
    "city_id": "371326"
  }, {
    "pinyin": "pingyuxian",
    "real": "平舆县",
    "city_id": "411723"
  }, {
    "pinyin": "pizhoushi",
    "real": "邳州市",
    "city_id": "320382"
  }, {
    "pinyin": "poyangxian",
    "real": "鄱阳县",
    "city_id": "361128"
  }, {
    "pinyin": "pucheng",
    "real": "蒲城",
    "city_id": "610526"
  }, {
    "pinyin": "puer",
    "real": "普洱",
    "city_id": "530800"
  }, {
    "pinyin": "pujiangxian",
    "real": "浦江县",
    "city_id": "330726"
  }, {
    "pinyin": "pulandianshi",
    "real": "普兰店市",
    "city_id": "210282"
  }, {
    "pinyin": "puningshi",
    "real": "普宁市",
    "city_id": "445281"
  }, {
    "pinyin": "putian",
    "real": "莆田",
    "city_id": "350300"
  }, {
    "pinyin": "puyang",
    "real": "濮阳",
    "city_id": "410900"
  }, {
    "pinyin": "puyangxian",
    "real": "濮阳县",
    "city_id": "410928"
  }],
  [{
    "pinyin": "qianan",
    "real": "乾安",
    "city_id": "220723"
  }, {
    "pinyin": "qiananshi",
    "real": "迁安市",
    "city_id": "130283"
  }, {
    "pinyin": "qianjiang",
    "real": "潜江",
    "city_id": "4290051"
  }, {
    "pinyin": "qianjiang",
    "real": "黔江",
    "city_id": "500114"
  }, {
    "pinyin": "qianshanxian",
    "real": "铅山县",
    "city_id": "361124"
  }, {
    "pinyin": "qianshanxian",
    "real": "潜山县",
    "city_id": "340824"
  }, {
    "pinyin": "qianxi",
    "real": "迁西",
    "city_id": "130227"
  }, {
    "pinyin": "qidongshi",
    "real": "启东市",
    "city_id": "320681"
  }, {
    "pinyin": "qidongxian",
    "real": "祁东县",
    "city_id": "430426"
  }, {
    "pinyin": "qihexian",
    "real": "齐河县",
    "city_id": "371425"
  }, {
    "pinyin": "qijiangxian",
    "real": "綦江县",
    "city_id": "500110"
  }, {
    "pinyin": "qingan",
    "real": "庆安",
    "city_id": "231224"
  }, {
    "pinyin": "qingchuan",
    "real": "青川",
    "city_id": "510822"
  }, {
    "pinyin": "qingdao",
    "real": "青岛",
    "city_id": "370200"
  }, {
    "pinyin": "qingfeng",
    "real": "清丰",
    "city_id": "410922"
  }, {
    "pinyin": "qinghexian",
    "real": "清河县",
    "city_id": "130534"
  }, {
    "pinyin": "qingshen",
    "real": "青神",
    "city_id": "511425"
  }, {
    "pinyin": "qingtianxian",
    "real": "青田县",
    "city_id": "331121"
  }, {
    "pinyin": "qingxian",
    "real": "青县",
    "city_id": "130922"
  }, {
    "pinyin": "qingyang",
    "real": "青阳",
    "city_id": "341723"
  }, {
    "pinyin": "qingyuan",
    "real": "清远",
    "city_id": "441800"
  }, {
    "pinyin": "qingyuan",
    "real": "庆元",
    "city_id": "331126"
  }, {
    "pinyin": "qingyuanmanzuzizhixian",
    "real": "清原满族自治县",
    "city_id": "210423"
  }, {
    "pinyin": "qingyuanxian",
    "real": "清苑县",
    "city_id": "130622"
  }, {
    "pinyin": "qingzhoushi",
    "real": "青州市",
    "city_id": "370781"
  }, {
    "pinyin": "qinhuangdao",
    "real": "秦皇岛",
    "city_id": "130300"
  }, {
    "pinyin": "qinyangshi",
    "real": "沁阳市",
    "city_id": "410882"
  }, {
    "pinyin": "qinzhou",
    "real": "钦州",
    "city_id": "450700"
  }, {
    "pinyin": "qionghai",
    "real": "琼海",
    "city_id": "469002"
  }, {
    "pinyin": "qionglaishi",
    "real": "邛崃市",
    "city_id": "510183"
  }, {
    "pinyin": "qiqihaer",
    "real": "齐齐哈尔",
    "city_id": "230200"
  }, {
    "pinyin": "qitaihe",
    "real": "七台河",
    "city_id": "230900"
  }, {
    "pinyin": "qixian",
    "real": "杞县",
    "city_id": "410221"
  }, {
    "pinyin": "qiyangxian",
    "real": "祁阳县",
    "city_id": "431121"
  }, {
    "pinyin": "quanjiaoxian",
    "real": "全椒县",
    "city_id": "341124"
  }, {
    "pinyin": "quanzhou",
    "real": "泉州",
    "city_id": "350500"
  }, {
    "pinyin": "qujiang",
    "real": "曲江",
    "city_id": "440205"
  }, {
    "pinyin": "qujing",
    "real": "曲靖",
    "city_id": "530300"
  }, {
    "pinyin": "quxian",
    "real": "渠县",
    "city_id": "511725"
  }, {
    "pinyin": "quzhou",
    "real": "衢州",
    "city_id": "330800"
  }, {
    "pinyin": "quzhou",
    "real": "曲周",
    "city_id": "130435"
  }],
  [{
    "pinyin": "renhua",
    "real": "仁化",
    "city_id": "440224"
  }, {
    "pinyin": "renqiushi",
    "real": "任丘市",
    "city_id": "130982"
  }, {
    "pinyin": "renshouxian",
    "real": "仁寿县",
    "city_id": "511421"
  }, {
    "pinyin": "rizhao",
    "real": "日照",
    "city_id": "371100"
  }, {
    "pinyin": "rongchangxian",
    "real": "荣昌县",
    "city_id": "500226"
  }, {
    "pinyin": "rongcheng",
    "real": "容城",
    "city_id": "130629"
  }, {
    "pinyin": "rongchengshi",
    "real": "荣成市",
    "city_id": "371082"
  }, {
    "pinyin": "rucheng",
    "real": "汝城",
    "city_id": "431026"
  }, {
    "pinyin": "rudongxian",
    "real": "如东县",
    "city_id": "320623"
  }, {
    "pinyin": "rugaoshi",
    "real": "如皋市",
    "city_id": "320682"
  }, {
    "pinyin": "ruichang",
    "real": "瑞昌",
    "city_id": "360481"
  }, {
    "pinyin": "ruijinshi",
    "real": "瑞金市",
    "city_id": "360781"
  }, {
    "pinyin": "ruili",
    "real": "瑞丽",
    "city_id": "533102"
  }, {
    "pinyin": "runanxian",
    "real": "汝南县",
    "city_id": "411727"
  }, {
    "pinyin": "rushanshi",
    "real": "乳山市",
    "city_id": "371083"
  }, {
    "pinyin": "ruyang",
    "real": "汝阳",
    "city_id": "410326"
  }, {
    "pinyin": "ruzhou",
    "real": "汝州",
    "city_id": "410482"
  }],
  [{
    "pinyin": "sangzhi",
    "real": "桑植",
    "city_id": "430822"
  }, {
    "pinyin": "sanmenxia",
    "real": "三门峡",
    "city_id": "411200"
  }, {
    "pinyin": "sanmenxian",
    "real": "三门县",
    "city_id": "331022"
  }, {
    "pinyin": "sanming",
    "real": "三明",
    "city_id": "350400"
  }, {
    "pinyin": "santaixian",
    "real": "三台县",
    "city_id": "510722"
  }, {
    "pinyin": "sanya",
    "real": "三亚",
    "city_id": "460200"
  }, {
    "pinyin": "sanyuan",
    "real": "三原",
    "city_id": "610422"
  }, {
    "pinyin": "shaheshi",
    "real": "沙河市",
    "city_id": "130582"
  }, {
    "pinyin": "shangcaixian",
    "real": "上蔡县",
    "city_id": "411722"
  }, {
    "pinyin": "shangcheng",
    "real": "商城",
    "city_id": "411524"
  }, {
    "pinyin": "shanggao",
    "real": "上高",
    "city_id": "360923"
  }, {
    "pinyin": "shanghai",
    "real": "上海",
    "city_id": "310100"
  }, {
    "pinyin": "shanglixian",
    "real": "上栗县",
    "city_id": "360322"
  }, {
    "pinyin": "shangluo",
    "real": "商洛",
    "city_id": "611000"
  }, {
    "pinyin": "shangqiu",
    "real": "商丘",
    "city_id": "411400"
  }, {
    "pinyin": "shangrao",
    "real": "上饶",
    "city_id": "361100"
  }, {
    "pinyin": "shangraoxian",
    "real": "上饶县",
    "city_id": "361121"
  }, {
    "pinyin": "shangshuixian",
    "real": "商水县",
    "city_id": "411623"
  }, {
    "pinyin": "shangyushi",
    "real": "上虞市",
    "city_id": "330682"
  }, {
    "pinyin": "shangzhishi",
    "real": "尚志市",
    "city_id": "230183"
  }, {
    "pinyin": "shantou",
    "real": "汕头",
    "city_id": "440500"
  }, {
    "pinyin": "shanwei",
    "real": "汕尾",
    "city_id": "441500"
  }, {
    "pinyin": "shanzhou",
    "real": "陕州",
    "city_id": "411222"
  }, {
    "pinyin": "shaodongxian",
    "real": "邵东县",
    "city_id": "430521"
  }, {
    "pinyin": "shaoguan",
    "real": "韶关",
    "city_id": "440200"
  }, {
    "pinyin": "shaoxing",
    "real": "绍兴",
    "city_id": "330600"
  }, {
    "pinyin": "shaoyang",
    "real": "邵阳",
    "city_id": "430500"
  }, {
    "pinyin": "shaxian",
    "real": "沙县",
    "city_id": "350427"
  }, {
    "pinyin": "shayangxian",
    "real": "沙洋县",
    "city_id": "420822"
  }, {
    "pinyin": "shehongxian",
    "real": "射洪县",
    "city_id": "510922"
  }, {
    "pinyin": "shenfangshi",
    "real": "什邡市",
    "city_id": "510682"
  }, {
    "pinyin": "shengzhoushi",
    "real": "嵊州市",
    "city_id": "330683"
  }, {
    "pinyin": "shenqiuxian",
    "real": "沈丘县",
    "city_id": "411624"
  }, {
    "pinyin": "shenyang",
    "real": "沈阳",
    "city_id": "210100"
  }, {
    "pinyin": "shenzhen",
    "real": "深圳",
    "city_id": "440300"
  }, {
    "pinyin": "shenzhoushi",
    "real": "深州市",
    "city_id": "131182"
  }, {
    "pinyin": "sheqixian",
    "real": "社旗县",
    "city_id": "411327"
  }, {
    "pinyin": "shexian",
    "real": "歙县",
    "city_id": "341021"
  }, {
    "pinyin": "sheyangxian",
    "real": "射阳县",
    "city_id": "320924"
  }, {
    "pinyin": "shicheng",
    "real": "石城",
    "city_id": "360735"
  }, {
    "pinyin": "shihezi",
    "real": "石河子",
    "city_id": "6590011"
  }, {
    "pinyin": "shijiazhuang",
    "real": "石家庄",
    "city_id": "130100"
  }, {
    "pinyin": "shilinyizuzizhixian",
    "real": "石林彝族自治县",
    "city_id": "530126"
  }, {
    "pinyin": "shishi",
    "real": "石狮",
    "city_id": "350581"
  }, {
    "pinyin": "shishoushi",
    "real": "石首市",
    "city_id": "421081"
  }, {
    "pinyin": "shixiang",
    "real": "始兴",
    "city_id": "440222"
  }, {
    "pinyin": "shiyan",
    "real": "十堰",
    "city_id": "420300"
  }, {
    "pinyin": "shizuishan",
    "real": "石嘴山",
    "city_id": "640200"
  }, {
    "pinyin": "shouguangshi",
    "real": "寿光市",
    "city_id": "370783"
  }, {
    "pinyin": "shouxian",
    "real": "寿县",
    "city_id": "341521"
  }, {
    "pinyin": "shuangchengshi",
    "real": "双城市",
    "city_id": "230182"
  }, {
    "pinyin": "shuangfengxian",
    "real": "双峰县",
    "city_id": "431321"
  }, {
    "pinyin": "shuangliaoshi",
    "real": "双辽市",
    "city_id": "220382"
  }, {
    "pinyin": "shuangyang",
    "real": "双阳",
    "city_id": "220112"
  }, {
    "pinyin": "shuchengxian",
    "real": "舒城县",
    "city_id": "341523"
  }, {
    "pinyin": "shulanshi",
    "real": "舒兰市",
    "city_id": "220283"
  }, {
    "pinyin": "shuozhou",
    "real": "朔州",
    "city_id": "140600"
  }, {
    "pinyin": "sihongxian",
    "real": "泗洪县",
    "city_id": "321324"
  }, {
    "pinyin": "sihuishi",
    "real": "四会市",
    "city_id": "441284"
  }, {
    "pinyin": "sinan",
    "real": "思南",
    "city_id": "520624"
  }, {
    "pinyin": "siping",
    "real": "四平",
    "city_id": "220300"
  }, {
    "pinyin": "sishui",
    "real": "泗水",
    "city_id": "370831"
  }, {
    "pinyin": "sixian",
    "real": "泗县",
    "city_id": "341324"
  }, {
    "pinyin": "siyangxian",
    "real": "泗阳县",
    "city_id": "321323"
  }, {
    "pinyin": "songtaomiaozuzizhixian",
    "real": "松桃苗族自治县",
    "city_id": "520628"
  }, {
    "pinyin": "songxi",
    "real": "松溪",
    "city_id": "350724"
  }, {
    "pinyin": "songxian",
    "real": "嵩县",
    "city_id": "410325"
  }, {
    "pinyin": "songyuan",
    "real": "松原",
    "city_id": "220700"
  }, {
    "pinyin": "songzishi",
    "real": "松滋市",
    "city_id": "421087"
  }, {
    "pinyin": "suichang",
    "real": "遂昌",
    "city_id": "331123"
  }, {
    "pinyin": "suichuan",
    "real": "遂川",
    "city_id": "360827"
  }, {
    "pinyin": "suihua",
    "real": "绥化",
    "city_id": "231200"
  }, {
    "pinyin": "suileng",
    "real": "绥棱",
    "city_id": "231226"
  }, {
    "pinyin": "suining",
    "real": "遂宁",
    "city_id": "510900"
  }, {
    "pinyin": "suining",
    "real": "绥宁",
    "city_id": "430527"
  }, {
    "pinyin": "suiningxian",
    "real": "睢宁县",
    "city_id": "320324"
  }, {
    "pinyin": "suiping",
    "real": "遂平",
    "city_id": "411728"
  }, {
    "pinyin": "suixian",
    "real": "睢县",
    "city_id": "411422"
  }, {
    "pinyin": "suixixian",
    "real": "濉溪县",
    "city_id": "340621"
  }, {
    "pinyin": "suiyang",
    "real": "绥阳",
    "city_id": "520323"
  }, {
    "pinyin": "suizhongxian",
    "real": "绥中县",
    "city_id": "211421"
  }, {
    "pinyin": "suizhou",
    "real": "随州",
    "city_id": "421300"
  }, {
    "pinyin": "suning",
    "real": "肃宁",
    "city_id": "130926"
  }, {
    "pinyin": "suqian",
    "real": "宿迁",
    "city_id": "321300"
  }, {
    "pinyin": "susong",
    "real": "宿松",
    "city_id": "340826"
  }, {
    "pinyin": "suzhou",
    "real": "苏州",
    "city_id": "320500"
  }, {
    "pinyin": "suzhou",
    "real": "宿州",
    "city_id": "341300"
  }],
  [{
    "pinyin": "taian",
    "real": "泰安",
    "city_id": "370900"
  }, {
    "pinyin": "taian",
    "real": "台安",
    "city_id": "210321"
  }, {
    "pinyin": "taigu",
    "real": "太谷",
    "city_id": "140726"
  }, {
    "pinyin": "taihexian",
    "real": "太和县",
    "city_id": "341222"
  }, {
    "pinyin": "taihexian",
    "real": "泰和县",
    "city_id": "360826"
  }, {
    "pinyin": "taikangxian",
    "real": "太康县",
    "city_id": "411627"
  }, {
    "pinyin": "taiqian",
    "real": "台前",
    "city_id": "410927"
  }, {
    "pinyin": "taishanshi",
    "real": "台山市",
    "city_id": "440781"
  }, {
    "pinyin": "taixingshi",
    "real": "泰兴市",
    "city_id": "321283"
  }, {
    "pinyin": "taiyuan",
    "real": "太原",
    "city_id": "140100"
  }, {
    "pinyin": "taizhou",
    "real": "泰州",
    "city_id": "321200"
  }, {
    "pinyin": "taizhou2",
    "real": "台州",
    "city_id": "331000"
  }, {
    "pinyin": "tanchengxian",
    "real": "郯城县",
    "city_id": "371322"
  }, {
    "pinyin": "tanghexian",
    "real": "唐河县",
    "city_id": "411328"
  }, {
    "pinyin": "tangshan",
    "real": "唐山",
    "city_id": "130200"
  }, {
    "pinyin": "tangyin",
    "real": "汤阴",
    "city_id": "410523"
  }, {
    "pinyin": "taojiangxian",
    "real": "桃江县",
    "city_id": "430922"
  }, {
    "pinyin": "taonanshi",
    "real": "洮南市",
    "city_id": "220881"
  }, {
    "pinyin": "taoyuanxian",
    "real": "桃源县",
    "city_id": "430725"
  }, {
    "pinyin": "tengchongxian",
    "real": "腾冲县",
    "city_id": "530522"
  }, {
    "pinyin": "tianchangshi",
    "real": "天长市",
    "city_id": "341181"
  }, {
    "pinyin": "tianjin",
    "real": "天津",
    "city_id": "120100"
  }, {
    "pinyin": "tianmen",
    "real": "天门",
    "city_id": "4290061"
  }, {
    "pinyin": "tianshui",
    "real": "天水",
    "city_id": "620500"
  }, {
    "pinyin": "tiantaixian",
    "real": "天台县",
    "city_id": "331023"
  }, {
    "pinyin": "tieling",
    "real": "铁岭",
    "city_id": "211200"
  }, {
    "pinyin": "tielishi",
    "real": "铁力市",
    "city_id": "230781"
  }, {
    "pinyin": "tongbo",
    "real": "桐柏",
    "city_id": "411330"
  }, {
    "pinyin": "tongcheng",
    "real": "通城",
    "city_id": "421222"
  }, {
    "pinyin": "tongchengshi",
    "real": "桐城市",
    "city_id": "340881"
  }, {
    "pinyin": "tongchuan",
    "real": "铜川",
    "city_id": "610200"
  }, {
    "pinyin": "tonghai",
    "real": "通海",
    "city_id": "530423"
  }, {
    "pinyin": "tonghua",
    "real": "通化",
    "city_id": "220500"
  }, {
    "pinyin": "tongjiang",
    "real": "同江",
    "city_id": "230881"
  }, {
    "pinyin": "tongjiang",
    "real": "通江",
    "city_id": "511921"
  }, {
    "pinyin": "tongliangxian",
    "real": "铜梁县",
    "city_id": "500224"
  }, {
    "pinyin": "tongliao",
    "real": "通辽",
    "city_id": "150500"
  }, {
    "pinyin": "tongling",
    "real": "铜陵",
    "city_id": "340700"
  }, {
    "pinyin": "tongluxian",
    "real": "桐庐县",
    "city_id": "330122"
  }, {
    "pinyin": "tongnanxian",
    "real": "潼南县",
    "city_id": "500223"
  }, {
    "pinyin": "tongren",
    "real": "铜仁",
    "city_id": "520600"
  }, {
    "pinyin": "tongshan",
    "real": "通山",
    "city_id": "421224"
  }, {
    "pinyin": "tongxiangshi",
    "real": "桐乡市",
    "city_id": "330483"
  }, {
    "pinyin": "tongxuxian",
    "real": "通许县",
    "city_id": "410222"
  }, {
    "pinyin": "tongyu",
    "real": "通榆",
    "city_id": "220822"
  }, {
    "pinyin": "tuanfeng",
    "real": "团风",
    "city_id": "421121"
  }, {
    "pinyin": "tumotezuoqi",
    "real": "土默特左旗",
    "city_id": "150121"
  }, {
    "pinyin": "tuoketuo",
    "real": "托克托",
    "city_id": "150122"
  }, {
    "pinyin": "tuquan",
    "real": "突泉",
    "city_id": "152224"
  }],
  [

  ],
  [

  ],
  [{
    "pinyin": "wafangdianshi",
    "real": "瓦房店市",
    "city_id": "210281"
  }, {
    "pinyin": "wangcheng",
    "real": "望城",
    "city_id": "430112"
  }, {
    "pinyin": "wangkui",
    "real": "望奎",
    "city_id": "231221"
  }, {
    "pinyin": "wannian",
    "real": "万年",
    "city_id": "361129"
  }, {
    "pinyin": "wanning",
    "real": "万宁",
    "city_id": "4690061"
  }, {
    "pinyin": "wanquan",
    "real": "万全",
    "city_id": "130729"
  }, {
    "pinyin": "wanrong",
    "real": "万荣",
    "city_id": "140822"
  }, {
    "pinyin": "wanyuan",
    "real": "万源",
    "city_id": "511781"
  }, {
    "pinyin": "wanzai",
    "real": "万载",
    "city_id": "360922"
  }, {
    "pinyin": "weifang",
    "real": "潍坊",
    "city_id": "370700"
  }, {
    "pinyin": "weihai",
    "real": "威海",
    "city_id": "371000"
  }, {
    "pinyin": "weihuishi",
    "real": "卫辉市",
    "city_id": "410781"
  }, {
    "pinyin": "weinan",
    "real": "渭南",
    "city_id": "610500"
  }, {
    "pinyin": "weishanxian",
    "real": "微山县",
    "city_id": "370826"
  }, {
    "pinyin": "weishixian",
    "real": "尉氏县",
    "city_id": "410223"
  }, {
    "pinyin": "weixian",
    "real": "威县",
    "city_id": "130533"
  }, {
    "pinyin": "weiyuanxian",
    "real": "威远县",
    "city_id": "511024"
  }, {
    "pinyin": "wenanxian",
    "real": "文安县",
    "city_id": "131026"
  }, {
    "pinyin": "wenchang",
    "real": "文昌",
    "city_id": "469005"
  }, {
    "pinyin": "wendengshi",
    "real": "文登市",
    "city_id": "371081"
  }, {
    "pinyin": "wengniuteqi",
    "real": "翁牛特旗",
    "city_id": "150426"
  }, {
    "pinyin": "wengyuan",
    "real": "翁源",
    "city_id": "440229"
  }, {
    "pinyin": "wenshangxian",
    "real": "汶上县",
    "city_id": "370830"
  }, {
    "pinyin": "wenshanxian",
    "real": "文山县",
    "city_id": "532601"
  }, {
    "pinyin": "wenshanzhou",
    "real": "文山州",
    "city_id": "532600"
  }, {
    "pinyin": "wenxian",
    "real": "温县",
    "city_id": "410825"
  }, {
    "pinyin": "wenxixian",
    "real": "闻喜县",
    "city_id": "140823"
  }, {
    "pinyin": "wenzhou",
    "real": "温州",
    "city_id": "330300"
  }, {
    "pinyin": "woyangxian",
    "real": "涡阳县",
    "city_id": "341621"
  }, {
    "pinyin": "wuanshi",
    "real": "武安市",
    "city_id": "130481"
  }, {
    "pinyin": "wuchangshi",
    "real": "五常市",
    "city_id": "230184"
  }, {
    "pinyin": "wuchuanshi",
    "real": "吴川市",
    "city_id": "440883"
  }, {
    "pinyin": "wudixian",
    "real": "无棣县",
    "city_id": "371623"
  }, {
    "pinyin": "wugang",
    "real": "舞钢",
    "city_id": "410481"
  }, {
    "pinyin": "wugangshi",
    "real": "武冈市",
    "city_id": "430581"
  }, {
    "pinyin": "wuhai",
    "real": "乌海",
    "city_id": "150300"
  }, {
    "pinyin": "wuhan",
    "real": "武汉",
    "city_id": "420100"
  }, {
    "pinyin": "wuhexian",
    "real": "五河县",
    "city_id": "340322"
  }, {
    "pinyin": "wuhu",
    "real": "芜湖",
    "city_id": "340200"
  }, {
    "pinyin": "wuhuxian",
    "real": "芜湖县",
    "city_id": "340221"
  }, {
    "pinyin": "wulanchabu",
    "real": "乌兰察布",
    "city_id": "150900"
  }, {
    "pinyin": "wulanhaoteshi",
    "real": "乌兰浩特市",
    "city_id": "152201"
  }, {
    "pinyin": "wulateqianqi",
    "real": "乌拉特前旗",
    "city_id": "150823"
  }, {
    "pinyin": "wulian",
    "real": "五莲",
    "city_id": "371121"
  }, {
    "pinyin": "wulongxian",
    "real": "武隆县",
    "city_id": "500232"
  }, {
    "pinyin": "wulumuqi",
    "real": "乌鲁木齐",
    "city_id": "650100"
  }, {
    "pinyin": "wuming",
    "real": "武鸣",
    "city_id": "450122"
  }, {
    "pinyin": "wuning",
    "real": "武宁",
    "city_id": "360423"
  }, {
    "pinyin": "wusheng",
    "real": "武胜",
    "city_id": "511622"
  }, {
    "pinyin": "wuwei",
    "real": "武威",
    "city_id": "620600"
  }, {
    "pinyin": "wuweixian",
    "real": "无为县",
    "city_id": "340225"
  }, {
    "pinyin": "wuxi",
    "real": "无锡",
    "city_id": "320200"
  }, {
    "pinyin": "wuxueshi",
    "real": "武穴市",
    "city_id": "421182"
  }, {
    "pinyin": "wuyangxian",
    "real": "舞阳县",
    "city_id": "411121"
  }, {
    "pinyin": "wuyishan",
    "real": "武夷山",
    "city_id": "350782"
  }, {
    "pinyin": "wuyixian",
    "real": "武义县",
    "city_id": "330723"
  }, {
    "pinyin": "wuyuan",
    "real": "五原",
    "city_id": "150821"
  }, {
    "pinyin": "wuzhixian",
    "real": "武陟县",
    "city_id": "410823"
  }, {
    "pinyin": "wuzhong",
    "real": "吴忠",
    "city_id": "640300"
  }, {
    "pinyin": "wuzhou",
    "real": "梧州",
    "city_id": "450400"
  }],
  [{
    "pinyin": "xiamen",
    "real": "厦门",
    "city_id": "350200"
  }, {
    "pinyin": "xian",
    "real": "西安",
    "city_id": "610100"
  }, {
    "pinyin": "xiangchengshi",
    "real": "项城市",
    "city_id": "411681"
  }, {
    "pinyin": "xiangchengxian",
    "real": "襄城县",
    "city_id": "411025"
  }, {
    "pinyin": "xiangfu",
    "real": "祥符",
    "city_id": "410224"
  }, {
    "pinyin": "xianghexian",
    "real": "香河县",
    "city_id": "131024"
  }, {
    "pinyin": "xiangshanxian",
    "real": "象山县",
    "city_id": "330225"
  }, {
    "pinyin": "xiangshuixian",
    "real": "响水县",
    "city_id": "320921"
  }, {
    "pinyin": "xiangtan",
    "real": "湘潭",
    "city_id": "430300"
  }, {
    "pinyin": "xiangtanxian",
    "real": "湘潭县",
    "city_id": "430321"
  }, {
    "pinyin": "xiangxiangshi",
    "real": "湘乡市",
    "city_id": "430381"
  }, {
    "pinyin": "xiangyang",
    "real": "襄阳",
    "city_id": "420600"
  }, {
    "pinyin": "xiangyinxian",
    "real": "湘阴县",
    "city_id": "430624"
  }, {
    "pinyin": "xiangyunxian",
    "real": "祥云县",
    "city_id": "532923"
  }, {
    "pinyin": "xianjuxian",
    "real": "仙居县",
    "city_id": "331024"
  }, {
    "pinyin": "xianning",
    "real": "咸宁",
    "city_id": "421200"
  }, {
    "pinyin": "xiantao",
    "real": "仙桃",
    "city_id": "4290041"
  }, {
    "pinyin": "xianxian",
    "real": "献县",
    "city_id": "130929"
  }, {
    "pinyin": "xianyang",
    "real": "咸阳",
    "city_id": "610400"
  }, {
    "pinyin": "xianyouxian",
    "real": "仙游县",
    "city_id": "350322"
  }, {
    "pinyin": "xiaochangxian",
    "real": "孝昌县",
    "city_id": "420921"
  }, {
    "pinyin": "xiaogan",
    "real": "孝感",
    "city_id": "420900"
  }, {
    "pinyin": "xiaoxian",
    "real": "萧县",
    "city_id": "341322"
  }, {
    "pinyin": "xiaoyishi",
    "real": "孝义市",
    "city_id": "141181"
  }, {
    "pinyin": "xiapuxian",
    "real": "霞浦县",
    "city_id": "350921"
  }, {
    "pinyin": "xiaxian",
    "real": "夏县",
    "city_id": "140828"
  }, {
    "pinyin": "xiayixian",
    "real": "夏邑县",
    "city_id": "411426"
  }, {
    "pinyin": "xichang",
    "real": "西昌",
    "city_id": "513401"
  }, {
    "pinyin": "xichong",
    "real": "西充",
    "city_id": "511325"
  }, {
    "pinyin": "xichuanxian",
    "real": "淅川县",
    "city_id": "411326"
  }, {
    "pinyin": "xifeng",
    "real": "西丰",
    "city_id": "211223"
  }, {
    "pinyin": "xihuaxian",
    "real": "西华县",
    "city_id": "411622"
  }, {
    "pinyin": "xilinhaoteshi",
    "real": "锡林浩特市",
    "city_id": "152502"
  }, {
    "pinyin": "xinanxian",
    "real": "新安县",
    "city_id": "410323"
  }, {
    "pinyin": "xinbinmanzuzizhixian",
    "real": "新宾满族自治县",
    "city_id": "210422"
  }, {
    "pinyin": "xincaixian",
    "real": "新蔡县",
    "city_id": "411729"
  }, {
    "pinyin": "xinchangxian",
    "real": "新昌县",
    "city_id": "330624"
  }, {
    "pinyin": "xinfengxian",
    "real": "信丰县",
    "city_id": "360722"
  }, {
    "pinyin": "xingan",
    "real": "新干",
    "city_id": "360824"
  }, {
    "pinyin": "xingchengshi",
    "real": "兴城市",
    "city_id": "211481"
  }, {
    "pinyin": "xingguoxian",
    "real": "兴国县",
    "city_id": "360732"
  }, {
    "pinyin": "xinghuashi",
    "real": "兴化市",
    "city_id": "321281"
  }, {
    "pinyin": "xingningshi",
    "real": "兴宁市",
    "city_id": "441481"
  }, {
    "pinyin": "xingping",
    "real": "兴平",
    "city_id": "610481"
  }, {
    "pinyin": "xingtai",
    "real": "邢台",
    "city_id": "130500"
  }, {
    "pinyin": "xingyishi",
    "real": "兴义市",
    "city_id": "522301"
  }, {
    "pinyin": "xingzi",
    "real": "星子",
    "city_id": "360427"
  }, {
    "pinyin": "xinhuaxian",
    "real": "新化县",
    "city_id": "431322"
  }, {
    "pinyin": "xining",
    "real": "西宁",
    "city_id": "630100"
  }, {
    "pinyin": "xinjiang",
    "real": "新绛",
    "city_id": "140825"
  }, {
    "pinyin": "xinjinxian",
    "real": "新津县",
    "city_id": "510132"
  }, {
    "pinyin": "xinjishi",
    "real": "辛集市",
    "city_id": "130181"
  }, {
    "pinyin": "xinmishi",
    "real": "新密市",
    "city_id": "410183"
  }, {
    "pinyin": "xinningxian",
    "real": "新宁县",
    "city_id": "430528"
  }, {
    "pinyin": "xintaishi",
    "real": "新泰市",
    "city_id": "370982"
  }, {
    "pinyin": "xintian",
    "real": "新田",
    "city_id": "431128"
  }, {
    "pinyin": "xinxian",
    "real": "莘县",
    "city_id": "371522"
  }, {
    "pinyin": "xinxian",
    "real": "新县",
    "city_id": "411523"
  }, {
    "pinyin": "xinxiang",
    "real": "新乡",
    "city_id": "410700"
  }, {
    "pinyin": "xinxiangxian",
    "real": "新乡县",
    "city_id": "410721"
  }, {
    "pinyin": "xinxing",
    "real": "新兴",
    "city_id": "445321"
  }, {
    "pinyin": "xinyang",
    "real": "信阳",
    "city_id": "411500"
  }, {
    "pinyin": "xinyexian",
    "real": "新野县",
    "city_id": "411329"
  }, {
    "pinyin": "xinyishi",
    "real": "新沂市",
    "city_id": "320381"
  }, {
    "pinyin": "xinyishi",
    "real": "信宜市",
    "city_id": "440983"
  }, {
    "pinyin": "xinyu",
    "real": "新余",
    "city_id": "360500"
  }, {
    "pinyin": "xinzhou",
    "real": "忻州",
    "city_id": "140900"
  }, {
    "pinyin": "xinzhou",
    "real": "新洲",
    "city_id": "420117"
  }, {
    "pinyin": "xiongxian",
    "real": "雄县",
    "city_id": "130638"
  }, {
    "pinyin": "xipingxian",
    "real": "西平县",
    "city_id": "411721"
  }, {
    "pinyin": "xishui",
    "real": "习水",
    "city_id": "520330"
  }, {
    "pinyin": "xishuixian",
    "real": "浠水县",
    "city_id": "421125"
  }, {
    "pinyin": "xiushuixian",
    "real": "修水县",
    "city_id": "360424"
  }, {
    "pinyin": "xiuwu",
    "real": "修武",
    "city_id": "410821"
  }, {
    "pinyin": "xiuyanmanzuzizhixian",
    "real": "岫岩满族自治县",
    "city_id": "210323"
  }, {
    "pinyin": "xixian",
    "real": "息县",
    "city_id": "411528"
  }, {
    "pinyin": "xixiaxian",
    "real": "西峡县",
    "city_id": "411323"
  }, {
    "pinyin": "xuancheng",
    "real": "宣城",
    "city_id": "341800"
  }, {
    "pinyin": "xuanhanxian",
    "real": "宣汉县",
    "city_id": "511722"
  }, {
    "pinyin": "xuanweishi",
    "real": "宣威市",
    "city_id": "530381"
  }, {
    "pinyin": "xuchang",
    "real": "许昌",
    "city_id": "411000"
  }, {
    "pinyin": "xunwu",
    "real": "寻乌",
    "city_id": "360734"
  }, {
    "pinyin": "xupuxian",
    "real": "溆浦县",
    "city_id": "431224"
  }, {
    "pinyin": "xushuixian",
    "real": "徐水县",
    "city_id": "130625"
  }, {
    "pinyin": "xuyong",
    "real": "叙永",
    "city_id": "510524"
  }, {
    "pinyin": "xuzhou",
    "real": "徐州",
    "city_id": "320300"
  }],
  [{
    "pinyin": "xingyangshi",
    "real": "荥阳市",
    "city_id": "410182"
  }, {
    "pinyin": "yaan",
    "real": "雅安",
    "city_id": "511800"
  }, {
    "pinyin": "yakeshishi",
    "real": "牙克石市",
    "city_id": "150782"
  }, {
    "pinyin": "yanan",
    "real": "延安",
    "city_id": "610600"
  }, {
    "pinyin": "yanbianchaoxianzuzizhizhou",
    "real": "延边朝鲜族自治州",
    "city_id": "222400"
  }, {
    "pinyin": "yancheng",
    "real": "盐城",
    "city_id": "320900"
  }, {
    "pinyin": "yanchi",
    "real": "盐池",
    "city_id": "640323"
  }, {
    "pinyin": "yangchunshi",
    "real": "阳春市",
    "city_id": "441781"
  }, {
    "pinyin": "yangguxian",
    "real": "阳谷县",
    "city_id": "371521"
  }, {
    "pinyin": "yangjiang",
    "real": "阳江",
    "city_id": "441700"
  }, {
    "pinyin": "yangling",
    "real": "杨陵",
    "city_id": "610403"
  }, {
    "pinyin": "yangquan",
    "real": "阳泉",
    "city_id": "140300"
  }, {
    "pinyin": "yangshuo",
    "real": "阳朔",
    "city_id": "450321"
  }, {
    "pinyin": "yangxi",
    "real": "阳西",
    "city_id": "441721"
  }, {
    "pinyin": "yangxinxian",
    "real": "阳新县",
    "city_id": "420222"
  }, {
    "pinyin": "yangzhongshi",
    "real": "扬中市",
    "city_id": "321182"
  }, {
    "pinyin": "yangzhou",
    "real": "扬州",
    "city_id": "321000"
  }, {
    "pinyin": "yanjin",
    "real": "延津",
    "city_id": "410726"
  }, {
    "pinyin": "yanliang",
    "real": "阎良",
    "city_id": "610114"
  }, {
    "pinyin": "yanlingxian",
    "real": "鄢陵县",
    "city_id": "411024"
  }, {
    "pinyin": "yanqingxian",
    "real": "延庆县",
    "city_id": "110229"
  }, {
    "pinyin": "yanshanxian",
    "real": "砚山县",
    "city_id": "532622"
  }, {
    "pinyin": "yanshishi",
    "real": "偃师市",
    "city_id": "410381"
  }, {
    "pinyin": "yantai",
    "real": "烟台",
    "city_id": "370600"
  }, {
    "pinyin": "yanting",
    "real": "盐亭",
    "city_id": "510723"
  }, {
    "pinyin": "yanzhoushi",
    "real": "兖州市",
    "city_id": "370882"
  }, {
    "pinyin": "yexian",
    "real": "叶县",
    "city_id": "410422"
  }, {
    "pinyin": "yian",
    "real": "依安",
    "city_id": "230223"
  }, {
    "pinyin": "yibin",
    "real": "宜宾",
    "city_id": "511500"
  }, {
    "pinyin": "yibinxian",
    "real": "宜宾县",
    "city_id": "511521"
  }, {
    "pinyin": "yichang",
    "real": "宜昌",
    "city_id": "420500"
  }, {
    "pinyin": "yichengshi",
    "real": "宜城市",
    "city_id": "420684"
  }, {
    "pinyin": "yichuanxian",
    "real": "伊川县",
    "city_id": "410329"
  }, {
    "pinyin": "yichun",
    "real": "宜春",
    "city_id": "360900"
  }, {
    "pinyin": "yidoushi",
    "real": "宜都市",
    "city_id": "420581"
  }, {
    "pinyin": "yifeng",
    "real": "宜丰",
    "city_id": "360924"
  }, {
    "pinyin": "yijinhuoluoqi",
    "real": "伊金霍洛旗",
    "city_id": "150627"
  }, {
    "pinyin": "yiliangxian",
    "real": "宜良县",
    "city_id": "530125"
  }, {
    "pinyin": "yima",
    "real": "义马",
    "city_id": "411281"
  }, {
    "pinyin": "yinanxian",
    "real": "沂南县",
    "city_id": "371321"
  }, {
    "pinyin": "yinchuan",
    "real": "银川",
    "city_id": "640100"
  }, {
    "pinyin": "yingchengshi",
    "real": "应城市",
    "city_id": "420981"
  }, {
    "pinyin": "yingdeshi",
    "real": "英德市",
    "city_id": "441881"
  }, {
    "pinyin": "yingkou",
    "real": "营口",
    "city_id": "210800"
  }, {
    "pinyin": "yingshan",
    "real": "英山",
    "city_id": "421124"
  }, {
    "pinyin": "yingshangxian",
    "real": "颍上县",
    "city_id": "341226"
  }, {
    "pinyin": "yingshanxian",
    "real": "营山县",
    "city_id": "511322"
  }, {
    "pinyin": "yingtan",
    "real": "鹰潭",
    "city_id": "360600"
  }, {
    "pinyin": "yiningshi",
    "real": "伊宁市",
    "city_id": "654002"
  }, {
    "pinyin": "yishuixian",
    "real": "沂水县",
    "city_id": "371323"
  }, {
    "pinyin": "yitongmanzuzizhixian",
    "real": "伊通满族自治县",
    "city_id": "220323"
  }, {
    "pinyin": "yiwu",
    "real": "义乌",
    "city_id": "330782"
  }, {
    "pinyin": "yixian",
    "real": "义县",
    "city_id": "210727"
  }, {
    "pinyin": "yiyang",
    "real": "益阳",
    "city_id": "430900"
  }, {
    "pinyin": "yiyang",
    "real": "弋阳",
    "city_id": "361126"
  }, {
    "pinyin": "yiyang",
    "real": "宜阳",
    "city_id": "410327"
  }, {
    "pinyin": "yizhangxian",
    "real": "宜章县",
    "city_id": "431022"
  }, {
    "pinyin": "yizhengshi",
    "real": "仪征市",
    "city_id": "321081"
  }, {
    "pinyin": "yizhou",
    "real": "宜州",
    "city_id": "451281"
  }, {
    "pinyin": "yonganshi",
    "real": "永安市",
    "city_id": "350481"
  }, {
    "pinyin": "yongchengshi",
    "real": "永城市",
    "city_id": "411481"
  }, {
    "pinyin": "yongchunxian",
    "real": "永春县",
    "city_id": "350525"
  }, {
    "pinyin": "yongjiaxian",
    "real": "永嘉县",
    "city_id": "330324"
  }, {
    "pinyin": "yongjishi",
    "real": "永济市",
    "city_id": "140881"
  }, {
    "pinyin": "yongnianxian",
    "real": "永年县",
    "city_id": "130429"
  }, {
    "pinyin": "yongqing",
    "real": "永清",
    "city_id": "131023"
  }, {
    "pinyin": "yongshunxian",
    "real": "永顺县",
    "city_id": "433127"
  }, {
    "pinyin": "yongtai",
    "real": "永泰",
    "city_id": "350125"
  }, {
    "pinyin": "yongxingxian",
    "real": "永兴县",
    "city_id": "431023"
  }, {
    "pinyin": "yongxiuxian",
    "real": "永修县",
    "city_id": "360425"
  }, {
    "pinyin": "yongzhou",
    "real": "永州",
    "city_id": "431100"
  }, {
    "pinyin": "youxian",
    "real": "攸县",
    "city_id": "430223"
  }, {
    "pinyin": "youxixian",
    "real": "尤溪县",
    "city_id": "350426"
  }, {
    "pinyin": "youyangtujiazumiaozuzizhixian",
    "real": "酉阳土家族苗族自治县",
    "city_id": "500242"
  }, {
    "pinyin": "yuanan",
    "real": "远安",
    "city_id": "420525"
  }, {
    "pinyin": "yuanbaoshan",
    "real": "元宝山",
    "city_id": "150403"
  }, {
    "pinyin": "yuanjiangshi",
    "real": "沅江市",
    "city_id": "430981"
  }, {
    "pinyin": "yuanlingxian",
    "real": "沅陵县",
    "city_id": "431222"
  }, {
    "pinyin": "yuanpingshi",
    "real": "原平市",
    "city_id": "140981"
  }, {
    "pinyin": "yuanyangxian",
    "real": "原阳县",
    "city_id": "410725"
  }, {
    "pinyin": "yuchengshi",
    "real": "禹城市",
    "city_id": "371482"
  }, {
    "pinyin": "yuchengxian",
    "real": "虞城县",
    "city_id": "411425"
  }, {
    "pinyin": "yuduxian",
    "real": "于都县",
    "city_id": "360731"
  }, {
    "pinyin": "yuechixian",
    "real": "岳池县",
    "city_id": "511621"
  }, {
    "pinyin": "yueyang",
    "real": "岳阳",
    "city_id": "430600"
  }, {
    "pinyin": "yueyangxian",
    "real": "岳阳县",
    "city_id": "430621"
  }, {
    "pinyin": "yuganxian",
    "real": "余干县",
    "city_id": "361127"
  }, {
    "pinyin": "yuhuanxian",
    "real": "玉环县",
    "city_id": "331021"
  }, {
    "pinyin": "yujiang",
    "real": "余江",
    "city_id": "360622"
  }, {
    "pinyin": "yulin",
    "real": "榆林",
    "city_id": "610800"
  }, {
    "pinyin": "yulin",
    "real": "玉林",
    "city_id": "450900"
  }, {
    "pinyin": "yuncheng",
    "real": "运城",
    "city_id": "140800"
  }, {
    "pinyin": "yunchengxian",
    "real": "郓城县",
    "city_id": "371725"
  }, {
    "pinyin": "yunfu",
    "real": "云浮",
    "city_id": "445300"
  }, {
    "pinyin": "yunmengxian",
    "real": "云梦县",
    "city_id": "420923"
  }, {
    "pinyin": "yunyangxian",
    "real": "云阳县",
    "city_id": "500235"
  }, {
    "pinyin": "yushanxian",
    "real": "玉山县",
    "city_id": "361123"
  }, {
    "pinyin": "yushushi",
    "real": "榆树市",
    "city_id": "220182"
  }, {
    "pinyin": "yutai",
    "real": "鱼台",
    "city_id": "370827"
  }, {
    "pinyin": "yutianxian",
    "real": "玉田县",
    "city_id": "130229"
  }, {
    "pinyin": "yuxi",
    "real": "玉溪",
    "city_id": "530400"
  }, {
    "pinyin": "yuzhong",
    "real": "榆中",
    "city_id": "620123"
  }, {
    "pinyin": "yuzhoushi",
    "real": "禹州市",
    "city_id": "411081"
  }],
  [{
    "pinyin": "zanhuang",
    "real": "赞皇",
    "city_id": "130129"
  }, {
    "pinyin": "zaoqiang",
    "real": "枣强",
    "city_id": "131121"
  }, {
    "pinyin": "zaoyangshi",
    "real": "枣阳市",
    "city_id": "420683"
  }, {
    "pinyin": "zaozhuang",
    "real": "枣庄",
    "city_id": "370400"
  }, {
    "pinyin": "zhalaiteqi",
    "real": "扎赉特旗",
    "city_id": "152223"
  }, {
    "pinyin": "zhalantun",
    "real": "扎兰屯",
    "city_id": "150783"
  }, {
    "pinyin": "zhaluteqi",
    "real": "扎鲁特旗",
    "city_id": "150526"
  }, {
    "pinyin": "zhangjiajie",
    "real": "张家界",
    "city_id": "430800"
  }, {
    "pinyin": "zhangjiakou",
    "real": "张家口",
    "city_id": "130700"
  }, {
    "pinyin": "zhangping",
    "real": "漳平",
    "city_id": "350881"
  }, {
    "pinyin": "zhangpuxian",
    "real": "漳浦县",
    "city_id": "350623"
  }, {
    "pinyin": "zhangshushi",
    "real": "樟树市",
    "city_id": "360982"
  }, {
    "pinyin": "zhangwu",
    "real": "彰武",
    "city_id": "210922"
  }, {
    "pinyin": "zhangye",
    "real": "张掖",
    "city_id": "620700"
  }, {
    "pinyin": "zhangzhou",
    "real": "漳州",
    "city_id": "350600"
  }, {
    "pinyin": "zhanjiang",
    "real": "湛江",
    "city_id": "440800"
  }, {
    "pinyin": "zhanyixian",
    "real": "沾益县",
    "city_id": "530328"
  }, {
    "pinyin": "zhaoanxian",
    "real": "诏安县",
    "city_id": "350624"
  }, {
    "pinyin": "zhaodongshi",
    "real": "肇东市",
    "city_id": "231282"
  }, {
    "pinyin": "zhaoqing",
    "real": "肇庆",
    "city_id": "441200"
  }, {
    "pinyin": "zhaotong",
    "real": "昭通",
    "city_id": "530600"
  }, {
    "pinyin": "zhaoyuanshi",
    "real": "招远市",
    "city_id": "370685"
  }, {
    "pinyin": "zhechengxian",
    "real": "柘城县",
    "city_id": "411424"
  }, {
    "pinyin": "zhengdingxian",
    "real": "正定县",
    "city_id": "130123"
  }, {
    "pinyin": "zhenghe",
    "real": "政和",
    "city_id": "350725"
  }, {
    "pinyin": "zhengzhou",
    "real": "郑州",
    "city_id": "410100"
  }, {
    "pinyin": "zhenjiang",
    "real": "镇江",
    "city_id": "321100"
  }, {
    "pinyin": "zhenlai",
    "real": "镇赉",
    "city_id": "220821"
  }, {
    "pinyin": "zhenpingxian",
    "real": "镇平县",
    "city_id": "411324"
  }, {
    "pinyin": "zhenxiongxian",
    "real": "镇雄县",
    "city_id": "530627"
  }, {
    "pinyin": "zhijiangshi",
    "real": "枝江市",
    "city_id": "420583"
  }, {
    "pinyin": "zhongjiangxian",
    "real": "中江县",
    "city_id": "510623"
  }, {
    "pinyin": "zhongmouxian",
    "real": "中牟县",
    "city_id": "410122"
  }, {
    "pinyin": "zhongshan",
    "real": "中山",
    "city_id": "442000"
  }, {
    "pinyin": "zhongwei",
    "real": "中卫",
    "city_id": "640500"
  }, {
    "pinyin": "zhongxian",
    "real": "忠县",
    "city_id": "500233"
  }, {
    "pinyin": "zhongxiangshi",
    "real": "钟祥市",
    "city_id": "420881"
  }, {
    "pinyin": "zhoukou",
    "real": "周口",
    "city_id": "411600"
  }, {
    "pinyin": "zhoushan",
    "real": "舟山",
    "city_id": "330900"
  }, {
    "pinyin": "zhuangheshi",
    "real": "庄河市",
    "city_id": "210283"
  }, {
    "pinyin": "zhuchengshi",
    "real": "诸城市",
    "city_id": "370782"
  }, {
    "pinyin": "zhuhai",
    "real": "珠海",
    "city_id": "440400"
  }, {
    "pinyin": "zhujishi",
    "real": "诸暨市",
    "city_id": "330681"
  }, {
    "pinyin": "zhumadian",
    "real": "驻马店",
    "city_id": "411700"
  }, {
    "pinyin": "zhuozhou",
    "real": "涿州",
    "city_id": "130681"
  }, {
    "pinyin": "zhuzhou",
    "real": "株洲",
    "city_id": "430200"
  }, {
    "pinyin": "zibo",
    "real": "淄博",
    "city_id": "370300"
  }, {
    "pinyin": "zigong",
    "real": "自贡",
    "city_id": "510300"
  }, {
    "pinyin": "zigui",
    "real": "秭归",
    "city_id": "420527"
  }, {
    "pinyin": "zijinxian",
    "real": "紫金县",
    "city_id": "441621"
  }, {
    "pinyin": "zitong",
    "real": "梓潼",
    "city_id": "510725"
  }, {
    "pinyin": "ziyang",
    "real": "资阳",
    "city_id": "512000"
  }, {
    "pinyin": "zizhongxian",
    "real": "资中县",
    "city_id": "511025"
  }, {
    "pinyin": "zongyangxian",
    "real": "枞阳县",
    "city_id": "340823"
  }, {
    "pinyin": "zouchengshi",
    "real": "邹城市",
    "city_id": "370883"
  }, {
    "pinyin": "zoupingxian",
    "real": "邹平县",
    "city_id": "371626"
  }, {
    "pinyin": "zunhuashi",
    "real": "遵化市",
    "city_id": "130281"
  }, {
    "pinyin": "zunyi",
    "real": "遵义",
    "city_id": "520300"
  }]
];
export default data;
